spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate: 
      ddl-auto: update
  datasource: 
    url: jdbc:mysql://mysqlhost/reactivesw?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
grpc: 
  port : 6565
  sku:
    host: localhost
    port: 9096