// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shopping_cart_proto/shopping_cart_message.proto

package io.reactivesw.shoppingcart.grpc;

public interface AddRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string session_id = 1;</code>
   */
  java.lang.String getSessionId();
  /**
   * <code>optional string session_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>optional int64 customer_id = 2;</code>
   */
  long getCustomerId();

  /**
   * <code>optional int64 sku_id = 3;</code>
   */
  long getSkuId();

  /**
   * <code>optional int32 quantity = 4;</code>
   */
  int getQuantity();
}
