// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shopping_cart_proto/shopping_cart_message.proto

package io.reactivesw.shoppingcart.grpc;

/**
 * <pre>
 * The response message containing the shopping cart id.
 * </pre>
 *
 * Protobuf type {@code AddReply}
 */
public  final class AddReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AddReply)
    AddReplyOrBuilder {
  // Use AddReply.newBuilder() to construct.
  private AddReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddReply() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private AddReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            io.reactivesw.shoppingcart.grpc.GrpcShoppingCart.Builder subBuilder = null;
            if (shoppingCart_ != null) {
              subBuilder = shoppingCart_.toBuilder();
            }
            shoppingCart_ = input.readMessage(io.reactivesw.shoppingcart.grpc.GrpcShoppingCart.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(shoppingCart_);
              shoppingCart_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.reactivesw.shoppingcart.grpc.ShoppingCartMessage.internal_static_AddReply_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.reactivesw.shoppingcart.grpc.ShoppingCartMessage.internal_static_AddReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.reactivesw.shoppingcart.grpc.AddReply.class, io.reactivesw.shoppingcart.grpc.AddReply.Builder.class);
  }

  public static final int SHOPPINGCART_FIELD_NUMBER = 1;
  private io.reactivesw.shoppingcart.grpc.GrpcShoppingCart shoppingCart_;
  /**
   * <code>optional .GrpcShoppingCart shoppingCart = 1;</code>
   */
  public boolean hasShoppingCart() {
    return shoppingCart_ != null;
  }
  /**
   * <code>optional .GrpcShoppingCart shoppingCart = 1;</code>
   */
  public io.reactivesw.shoppingcart.grpc.GrpcShoppingCart getShoppingCart() {
    return shoppingCart_ == null ? io.reactivesw.shoppingcart.grpc.GrpcShoppingCart.getDefaultInstance() : shoppingCart_;
  }
  /**
   * <code>optional .GrpcShoppingCart shoppingCart = 1;</code>
   */
  public io.reactivesw.shoppingcart.grpc.GrpcShoppingCartOrBuilder getShoppingCartOrBuilder() {
    return getShoppingCart();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (shoppingCart_ != null) {
      output.writeMessage(1, getShoppingCart());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (shoppingCart_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getShoppingCart());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.reactivesw.shoppingcart.grpc.AddReply)) {
      return super.equals(obj);
    }
    io.reactivesw.shoppingcart.grpc.AddReply other = (io.reactivesw.shoppingcart.grpc.AddReply) obj;

    boolean result = true;
    result = result && (hasShoppingCart() == other.hasShoppingCart());
    if (hasShoppingCart()) {
      result = result && getShoppingCart()
          .equals(other.getShoppingCart());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasShoppingCart()) {
      hash = (37 * hash) + SHOPPINGCART_FIELD_NUMBER;
      hash = (53 * hash) + getShoppingCart().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.reactivesw.shoppingcart.grpc.AddReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.reactivesw.shoppingcart.grpc.AddReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.reactivesw.shoppingcart.grpc.AddReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.reactivesw.shoppingcart.grpc.AddReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.reactivesw.shoppingcart.grpc.AddReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.reactivesw.shoppingcart.grpc.AddReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.reactivesw.shoppingcart.grpc.AddReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.reactivesw.shoppingcart.grpc.AddReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.reactivesw.shoppingcart.grpc.AddReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.reactivesw.shoppingcart.grpc.AddReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.reactivesw.shoppingcart.grpc.AddReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The response message containing the shopping cart id.
   * </pre>
   *
   * Protobuf type {@code AddReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AddReply)
      io.reactivesw.shoppingcart.grpc.AddReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.reactivesw.shoppingcart.grpc.ShoppingCartMessage.internal_static_AddReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.reactivesw.shoppingcart.grpc.ShoppingCartMessage.internal_static_AddReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.reactivesw.shoppingcart.grpc.AddReply.class, io.reactivesw.shoppingcart.grpc.AddReply.Builder.class);
    }

    // Construct using io.reactivesw.shoppingcart.grpc.AddReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (shoppingCartBuilder_ == null) {
        shoppingCart_ = null;
      } else {
        shoppingCart_ = null;
        shoppingCartBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.reactivesw.shoppingcart.grpc.ShoppingCartMessage.internal_static_AddReply_descriptor;
    }

    public io.reactivesw.shoppingcart.grpc.AddReply getDefaultInstanceForType() {
      return io.reactivesw.shoppingcart.grpc.AddReply.getDefaultInstance();
    }

    public io.reactivesw.shoppingcart.grpc.AddReply build() {
      io.reactivesw.shoppingcart.grpc.AddReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.reactivesw.shoppingcart.grpc.AddReply buildPartial() {
      io.reactivesw.shoppingcart.grpc.AddReply result = new io.reactivesw.shoppingcart.grpc.AddReply(this);
      if (shoppingCartBuilder_ == null) {
        result.shoppingCart_ = shoppingCart_;
      } else {
        result.shoppingCart_ = shoppingCartBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.reactivesw.shoppingcart.grpc.AddReply) {
        return mergeFrom((io.reactivesw.shoppingcart.grpc.AddReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.reactivesw.shoppingcart.grpc.AddReply other) {
      if (other == io.reactivesw.shoppingcart.grpc.AddReply.getDefaultInstance()) return this;
      if (other.hasShoppingCart()) {
        mergeShoppingCart(other.getShoppingCart());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.reactivesw.shoppingcart.grpc.AddReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.reactivesw.shoppingcart.grpc.AddReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private io.reactivesw.shoppingcart.grpc.GrpcShoppingCart shoppingCart_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.reactivesw.shoppingcart.grpc.GrpcShoppingCart, io.reactivesw.shoppingcart.grpc.GrpcShoppingCart.Builder, io.reactivesw.shoppingcart.grpc.GrpcShoppingCartOrBuilder> shoppingCartBuilder_;
    /**
     * <code>optional .GrpcShoppingCart shoppingCart = 1;</code>
     */
    public boolean hasShoppingCart() {
      return shoppingCartBuilder_ != null || shoppingCart_ != null;
    }
    /**
     * <code>optional .GrpcShoppingCart shoppingCart = 1;</code>
     */
    public io.reactivesw.shoppingcart.grpc.GrpcShoppingCart getShoppingCart() {
      if (shoppingCartBuilder_ == null) {
        return shoppingCart_ == null ? io.reactivesw.shoppingcart.grpc.GrpcShoppingCart.getDefaultInstance() : shoppingCart_;
      } else {
        return shoppingCartBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .GrpcShoppingCart shoppingCart = 1;</code>
     */
    public Builder setShoppingCart(io.reactivesw.shoppingcart.grpc.GrpcShoppingCart value) {
      if (shoppingCartBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        shoppingCart_ = value;
        onChanged();
      } else {
        shoppingCartBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .GrpcShoppingCart shoppingCart = 1;</code>
     */
    public Builder setShoppingCart(
        io.reactivesw.shoppingcart.grpc.GrpcShoppingCart.Builder builderForValue) {
      if (shoppingCartBuilder_ == null) {
        shoppingCart_ = builderForValue.build();
        onChanged();
      } else {
        shoppingCartBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .GrpcShoppingCart shoppingCart = 1;</code>
     */
    public Builder mergeShoppingCart(io.reactivesw.shoppingcart.grpc.GrpcShoppingCart value) {
      if (shoppingCartBuilder_ == null) {
        if (shoppingCart_ != null) {
          shoppingCart_ =
            io.reactivesw.shoppingcart.grpc.GrpcShoppingCart.newBuilder(shoppingCart_).mergeFrom(value).buildPartial();
        } else {
          shoppingCart_ = value;
        }
        onChanged();
      } else {
        shoppingCartBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .GrpcShoppingCart shoppingCart = 1;</code>
     */
    public Builder clearShoppingCart() {
      if (shoppingCartBuilder_ == null) {
        shoppingCart_ = null;
        onChanged();
      } else {
        shoppingCart_ = null;
        shoppingCartBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .GrpcShoppingCart shoppingCart = 1;</code>
     */
    public io.reactivesw.shoppingcart.grpc.GrpcShoppingCart.Builder getShoppingCartBuilder() {
      
      onChanged();
      return getShoppingCartFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .GrpcShoppingCart shoppingCart = 1;</code>
     */
    public io.reactivesw.shoppingcart.grpc.GrpcShoppingCartOrBuilder getShoppingCartOrBuilder() {
      if (shoppingCartBuilder_ != null) {
        return shoppingCartBuilder_.getMessageOrBuilder();
      } else {
        return shoppingCart_ == null ?
            io.reactivesw.shoppingcart.grpc.GrpcShoppingCart.getDefaultInstance() : shoppingCart_;
      }
    }
    /**
     * <code>optional .GrpcShoppingCart shoppingCart = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.reactivesw.shoppingcart.grpc.GrpcShoppingCart, io.reactivesw.shoppingcart.grpc.GrpcShoppingCart.Builder, io.reactivesw.shoppingcart.grpc.GrpcShoppingCartOrBuilder> 
        getShoppingCartFieldBuilder() {
      if (shoppingCartBuilder_ == null) {
        shoppingCartBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.reactivesw.shoppingcart.grpc.GrpcShoppingCart, io.reactivesw.shoppingcart.grpc.GrpcShoppingCart.Builder, io.reactivesw.shoppingcart.grpc.GrpcShoppingCartOrBuilder>(
                getShoppingCart(),
                getParentForChildren(),
                isClean());
        shoppingCart_ = null;
      }
      return shoppingCartBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:AddReply)
  }

  // @@protoc_insertion_point(class_scope:AddReply)
  private static final io.reactivesw.shoppingcart.grpc.AddReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.reactivesw.shoppingcart.grpc.AddReply();
  }

  public static io.reactivesw.shoppingcart.grpc.AddReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddReply>
      PARSER = new com.google.protobuf.AbstractParser<AddReply>() {
    public AddReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AddReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddReply> getParserForType() {
    return PARSER;
  }

  public io.reactivesw.shoppingcart.grpc.AddReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

