// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shopping_cart_proto/shopping_cart_message.proto

package io.reactivesw.shoppingcart.grpc;

public interface CustomerShoppingCartListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CustomerShoppingCartListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 customer_id = 1;</code>
   */
  long getCustomerId();
}
