// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shopping_cart_proto/shopping_cart_message.proto

package io.reactivesw.shoppingcart.grpc;

/**
 * <pre>
 * The request message containing: customer id.
 * </pre>
 *
 * Protobuf type {@code CustomerShoppingCartListRequest}
 */
public  final class CustomerShoppingCartListRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CustomerShoppingCartListRequest)
    CustomerShoppingCartListRequestOrBuilder {
  // Use CustomerShoppingCartListRequest.newBuilder() to construct.
  private CustomerShoppingCartListRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CustomerShoppingCartListRequest() {
    customerId_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private CustomerShoppingCartListRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            customerId_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.reactivesw.shoppingcart.grpc.ShoppingCartMessage.internal_static_CustomerShoppingCartListRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.reactivesw.shoppingcart.grpc.ShoppingCartMessage.internal_static_CustomerShoppingCartListRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest.class, io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest.Builder.class);
  }

  public static final int CUSTOMER_ID_FIELD_NUMBER = 1;
  private long customerId_;
  /**
   * <code>optional int64 customer_id = 1;</code>
   */
  public long getCustomerId() {
    return customerId_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (customerId_ != 0L) {
      output.writeInt64(1, customerId_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (customerId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, customerId_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest)) {
      return super.equals(obj);
    }
    io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest other = (io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest) obj;

    boolean result = true;
    result = result && (getCustomerId()
        == other.getCustomerId());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + CUSTOMER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCustomerId());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The request message containing: customer id.
   * </pre>
   *
   * Protobuf type {@code CustomerShoppingCartListRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CustomerShoppingCartListRequest)
      io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.reactivesw.shoppingcart.grpc.ShoppingCartMessage.internal_static_CustomerShoppingCartListRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.reactivesw.shoppingcart.grpc.ShoppingCartMessage.internal_static_CustomerShoppingCartListRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest.class, io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest.Builder.class);
    }

    // Construct using io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      customerId_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.reactivesw.shoppingcart.grpc.ShoppingCartMessage.internal_static_CustomerShoppingCartListRequest_descriptor;
    }

    public io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest getDefaultInstanceForType() {
      return io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest.getDefaultInstance();
    }

    public io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest build() {
      io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest buildPartial() {
      io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest result = new io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest(this);
      result.customerId_ = customerId_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest) {
        return mergeFrom((io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest other) {
      if (other == io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest.getDefaultInstance()) return this;
      if (other.getCustomerId() != 0L) {
        setCustomerId(other.getCustomerId());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long customerId_ ;
    /**
     * <code>optional int64 customer_id = 1;</code>
     */
    public long getCustomerId() {
      return customerId_;
    }
    /**
     * <code>optional int64 customer_id = 1;</code>
     */
    public Builder setCustomerId(long value) {
      
      customerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 customer_id = 1;</code>
     */
    public Builder clearCustomerId() {
      
      customerId_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:CustomerShoppingCartListRequest)
  }

  // @@protoc_insertion_point(class_scope:CustomerShoppingCartListRequest)
  private static final io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest();
  }

  public static io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CustomerShoppingCartListRequest>
      PARSER = new com.google.protobuf.AbstractParser<CustomerShoppingCartListRequest>() {
    public CustomerShoppingCartListRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new CustomerShoppingCartListRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CustomerShoppingCartListRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CustomerShoppingCartListRequest> getParserForType() {
    return PARSER;
  }

  public io.reactivesw.shoppingcart.grpc.CustomerShoppingCartListRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

