// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shopping_cart_proto/shopping_cart_message.proto

package io.reactivesw.shoppingcart.grpc;

public interface ShoppingCartListReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ShoppingCartListReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
   */
  java.util.List<io.reactivesw.shoppingcart.grpc.GrpcShoppingCart> 
      getShoppingCartList();
  /**
   * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
   */
  io.reactivesw.shoppingcart.grpc.GrpcShoppingCart getShoppingCart(int index);
  /**
   * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
   */
  int getShoppingCartCount();
  /**
   * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
   */
  java.util.List<? extends io.reactivesw.shoppingcart.grpc.GrpcShoppingCartOrBuilder> 
      getShoppingCartOrBuilderList();
  /**
   * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
   */
  io.reactivesw.shoppingcart.grpc.GrpcShoppingCartOrBuilder getShoppingCartOrBuilder(
      int index);
}
