// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shopping_cart_proto/shopping_cart_message.proto

package io.reactivesw.shoppingcart.grpc;

/**
 * <pre>
 * The response message containing the shopping cart list.
 * </pre>
 *
 * Protobuf type {@code ShoppingCartListReply}
 */
public  final class ShoppingCartListReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ShoppingCartListReply)
    ShoppingCartListReplyOrBuilder {
  // Use ShoppingCartListReply.newBuilder() to construct.
  private ShoppingCartListReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ShoppingCartListReply() {
    shoppingCart_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ShoppingCartListReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              shoppingCart_ = new java.util.ArrayList<io.reactivesw.shoppingcart.grpc.GrpcShoppingCart>();
              mutable_bitField0_ |= 0x00000001;
            }
            shoppingCart_.add(
                input.readMessage(io.reactivesw.shoppingcart.grpc.GrpcShoppingCart.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        shoppingCart_ = java.util.Collections.unmodifiableList(shoppingCart_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.reactivesw.shoppingcart.grpc.ShoppingCartMessage.internal_static_ShoppingCartListReply_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.reactivesw.shoppingcart.grpc.ShoppingCartMessage.internal_static_ShoppingCartListReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.reactivesw.shoppingcart.grpc.ShoppingCartListReply.class, io.reactivesw.shoppingcart.grpc.ShoppingCartListReply.Builder.class);
  }

  public static final int SHOPPINGCART_FIELD_NUMBER = 1;
  private java.util.List<io.reactivesw.shoppingcart.grpc.GrpcShoppingCart> shoppingCart_;
  /**
   * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
   */
  public java.util.List<io.reactivesw.shoppingcart.grpc.GrpcShoppingCart> getShoppingCartList() {
    return shoppingCart_;
  }
  /**
   * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
   */
  public java.util.List<? extends io.reactivesw.shoppingcart.grpc.GrpcShoppingCartOrBuilder> 
      getShoppingCartOrBuilderList() {
    return shoppingCart_;
  }
  /**
   * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
   */
  public int getShoppingCartCount() {
    return shoppingCart_.size();
  }
  /**
   * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
   */
  public io.reactivesw.shoppingcart.grpc.GrpcShoppingCart getShoppingCart(int index) {
    return shoppingCart_.get(index);
  }
  /**
   * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
   */
  public io.reactivesw.shoppingcart.grpc.GrpcShoppingCartOrBuilder getShoppingCartOrBuilder(
      int index) {
    return shoppingCart_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < shoppingCart_.size(); i++) {
      output.writeMessage(1, shoppingCart_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < shoppingCart_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, shoppingCart_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.reactivesw.shoppingcart.grpc.ShoppingCartListReply)) {
      return super.equals(obj);
    }
    io.reactivesw.shoppingcart.grpc.ShoppingCartListReply other = (io.reactivesw.shoppingcart.grpc.ShoppingCartListReply) obj;

    boolean result = true;
    result = result && getShoppingCartList()
        .equals(other.getShoppingCartList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getShoppingCartCount() > 0) {
      hash = (37 * hash) + SHOPPINGCART_FIELD_NUMBER;
      hash = (53 * hash) + getShoppingCartList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.reactivesw.shoppingcart.grpc.ShoppingCartListReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.reactivesw.shoppingcart.grpc.ShoppingCartListReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.reactivesw.shoppingcart.grpc.ShoppingCartListReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.reactivesw.shoppingcart.grpc.ShoppingCartListReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.reactivesw.shoppingcart.grpc.ShoppingCartListReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.reactivesw.shoppingcart.grpc.ShoppingCartListReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.reactivesw.shoppingcart.grpc.ShoppingCartListReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.reactivesw.shoppingcart.grpc.ShoppingCartListReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.reactivesw.shoppingcart.grpc.ShoppingCartListReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.reactivesw.shoppingcart.grpc.ShoppingCartListReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.reactivesw.shoppingcart.grpc.ShoppingCartListReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The response message containing the shopping cart list.
   * </pre>
   *
   * Protobuf type {@code ShoppingCartListReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ShoppingCartListReply)
      io.reactivesw.shoppingcart.grpc.ShoppingCartListReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.reactivesw.shoppingcart.grpc.ShoppingCartMessage.internal_static_ShoppingCartListReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.reactivesw.shoppingcart.grpc.ShoppingCartMessage.internal_static_ShoppingCartListReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.reactivesw.shoppingcart.grpc.ShoppingCartListReply.class, io.reactivesw.shoppingcart.grpc.ShoppingCartListReply.Builder.class);
    }

    // Construct using io.reactivesw.shoppingcart.grpc.ShoppingCartListReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getShoppingCartFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (shoppingCartBuilder_ == null) {
        shoppingCart_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        shoppingCartBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.reactivesw.shoppingcart.grpc.ShoppingCartMessage.internal_static_ShoppingCartListReply_descriptor;
    }

    public io.reactivesw.shoppingcart.grpc.ShoppingCartListReply getDefaultInstanceForType() {
      return io.reactivesw.shoppingcart.grpc.ShoppingCartListReply.getDefaultInstance();
    }

    public io.reactivesw.shoppingcart.grpc.ShoppingCartListReply build() {
      io.reactivesw.shoppingcart.grpc.ShoppingCartListReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.reactivesw.shoppingcart.grpc.ShoppingCartListReply buildPartial() {
      io.reactivesw.shoppingcart.grpc.ShoppingCartListReply result = new io.reactivesw.shoppingcart.grpc.ShoppingCartListReply(this);
      int from_bitField0_ = bitField0_;
      if (shoppingCartBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          shoppingCart_ = java.util.Collections.unmodifiableList(shoppingCart_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.shoppingCart_ = shoppingCart_;
      } else {
        result.shoppingCart_ = shoppingCartBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.reactivesw.shoppingcart.grpc.ShoppingCartListReply) {
        return mergeFrom((io.reactivesw.shoppingcart.grpc.ShoppingCartListReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.reactivesw.shoppingcart.grpc.ShoppingCartListReply other) {
      if (other == io.reactivesw.shoppingcart.grpc.ShoppingCartListReply.getDefaultInstance()) return this;
      if (shoppingCartBuilder_ == null) {
        if (!other.shoppingCart_.isEmpty()) {
          if (shoppingCart_.isEmpty()) {
            shoppingCart_ = other.shoppingCart_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureShoppingCartIsMutable();
            shoppingCart_.addAll(other.shoppingCart_);
          }
          onChanged();
        }
      } else {
        if (!other.shoppingCart_.isEmpty()) {
          if (shoppingCartBuilder_.isEmpty()) {
            shoppingCartBuilder_.dispose();
            shoppingCartBuilder_ = null;
            shoppingCart_ = other.shoppingCart_;
            bitField0_ = (bitField0_ & ~0x00000001);
            shoppingCartBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getShoppingCartFieldBuilder() : null;
          } else {
            shoppingCartBuilder_.addAllMessages(other.shoppingCart_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.reactivesw.shoppingcart.grpc.ShoppingCartListReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.reactivesw.shoppingcart.grpc.ShoppingCartListReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<io.reactivesw.shoppingcart.grpc.GrpcShoppingCart> shoppingCart_ =
      java.util.Collections.emptyList();
    private void ensureShoppingCartIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        shoppingCart_ = new java.util.ArrayList<io.reactivesw.shoppingcart.grpc.GrpcShoppingCart>(shoppingCart_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.reactivesw.shoppingcart.grpc.GrpcShoppingCart, io.reactivesw.shoppingcart.grpc.GrpcShoppingCart.Builder, io.reactivesw.shoppingcart.grpc.GrpcShoppingCartOrBuilder> shoppingCartBuilder_;

    /**
     * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
     */
    public java.util.List<io.reactivesw.shoppingcart.grpc.GrpcShoppingCart> getShoppingCartList() {
      if (shoppingCartBuilder_ == null) {
        return java.util.Collections.unmodifiableList(shoppingCart_);
      } else {
        return shoppingCartBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
     */
    public int getShoppingCartCount() {
      if (shoppingCartBuilder_ == null) {
        return shoppingCart_.size();
      } else {
        return shoppingCartBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
     */
    public io.reactivesw.shoppingcart.grpc.GrpcShoppingCart getShoppingCart(int index) {
      if (shoppingCartBuilder_ == null) {
        return shoppingCart_.get(index);
      } else {
        return shoppingCartBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
     */
    public Builder setShoppingCart(
        int index, io.reactivesw.shoppingcart.grpc.GrpcShoppingCart value) {
      if (shoppingCartBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureShoppingCartIsMutable();
        shoppingCart_.set(index, value);
        onChanged();
      } else {
        shoppingCartBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
     */
    public Builder setShoppingCart(
        int index, io.reactivesw.shoppingcart.grpc.GrpcShoppingCart.Builder builderForValue) {
      if (shoppingCartBuilder_ == null) {
        ensureShoppingCartIsMutable();
        shoppingCart_.set(index, builderForValue.build());
        onChanged();
      } else {
        shoppingCartBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
     */
    public Builder addShoppingCart(io.reactivesw.shoppingcart.grpc.GrpcShoppingCart value) {
      if (shoppingCartBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureShoppingCartIsMutable();
        shoppingCart_.add(value);
        onChanged();
      } else {
        shoppingCartBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
     */
    public Builder addShoppingCart(
        int index, io.reactivesw.shoppingcart.grpc.GrpcShoppingCart value) {
      if (shoppingCartBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureShoppingCartIsMutable();
        shoppingCart_.add(index, value);
        onChanged();
      } else {
        shoppingCartBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
     */
    public Builder addShoppingCart(
        io.reactivesw.shoppingcart.grpc.GrpcShoppingCart.Builder builderForValue) {
      if (shoppingCartBuilder_ == null) {
        ensureShoppingCartIsMutable();
        shoppingCart_.add(builderForValue.build());
        onChanged();
      } else {
        shoppingCartBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
     */
    public Builder addShoppingCart(
        int index, io.reactivesw.shoppingcart.grpc.GrpcShoppingCart.Builder builderForValue) {
      if (shoppingCartBuilder_ == null) {
        ensureShoppingCartIsMutable();
        shoppingCart_.add(index, builderForValue.build());
        onChanged();
      } else {
        shoppingCartBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
     */
    public Builder addAllShoppingCart(
        java.lang.Iterable<? extends io.reactivesw.shoppingcart.grpc.GrpcShoppingCart> values) {
      if (shoppingCartBuilder_ == null) {
        ensureShoppingCartIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, shoppingCart_);
        onChanged();
      } else {
        shoppingCartBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
     */
    public Builder clearShoppingCart() {
      if (shoppingCartBuilder_ == null) {
        shoppingCart_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        shoppingCartBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
     */
    public Builder removeShoppingCart(int index) {
      if (shoppingCartBuilder_ == null) {
        ensureShoppingCartIsMutable();
        shoppingCart_.remove(index);
        onChanged();
      } else {
        shoppingCartBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
     */
    public io.reactivesw.shoppingcart.grpc.GrpcShoppingCart.Builder getShoppingCartBuilder(
        int index) {
      return getShoppingCartFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
     */
    public io.reactivesw.shoppingcart.grpc.GrpcShoppingCartOrBuilder getShoppingCartOrBuilder(
        int index) {
      if (shoppingCartBuilder_ == null) {
        return shoppingCart_.get(index);  } else {
        return shoppingCartBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
     */
    public java.util.List<? extends io.reactivesw.shoppingcart.grpc.GrpcShoppingCartOrBuilder> 
         getShoppingCartOrBuilderList() {
      if (shoppingCartBuilder_ != null) {
        return shoppingCartBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(shoppingCart_);
      }
    }
    /**
     * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
     */
    public io.reactivesw.shoppingcart.grpc.GrpcShoppingCart.Builder addShoppingCartBuilder() {
      return getShoppingCartFieldBuilder().addBuilder(
          io.reactivesw.shoppingcart.grpc.GrpcShoppingCart.getDefaultInstance());
    }
    /**
     * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
     */
    public io.reactivesw.shoppingcart.grpc.GrpcShoppingCart.Builder addShoppingCartBuilder(
        int index) {
      return getShoppingCartFieldBuilder().addBuilder(
          index, io.reactivesw.shoppingcart.grpc.GrpcShoppingCart.getDefaultInstance());
    }
    /**
     * <code>repeated .GrpcShoppingCart shoppingCart = 1;</code>
     */
    public java.util.List<io.reactivesw.shoppingcart.grpc.GrpcShoppingCart.Builder> 
         getShoppingCartBuilderList() {
      return getShoppingCartFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.reactivesw.shoppingcart.grpc.GrpcShoppingCart, io.reactivesw.shoppingcart.grpc.GrpcShoppingCart.Builder, io.reactivesw.shoppingcart.grpc.GrpcShoppingCartOrBuilder> 
        getShoppingCartFieldBuilder() {
      if (shoppingCartBuilder_ == null) {
        shoppingCartBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.reactivesw.shoppingcart.grpc.GrpcShoppingCart, io.reactivesw.shoppingcart.grpc.GrpcShoppingCart.Builder, io.reactivesw.shoppingcart.grpc.GrpcShoppingCartOrBuilder>(
                shoppingCart_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        shoppingCart_ = null;
      }
      return shoppingCartBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:ShoppingCartListReply)
  }

  // @@protoc_insertion_point(class_scope:ShoppingCartListReply)
  private static final io.reactivesw.shoppingcart.grpc.ShoppingCartListReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.reactivesw.shoppingcart.grpc.ShoppingCartListReply();
  }

  public static io.reactivesw.shoppingcart.grpc.ShoppingCartListReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ShoppingCartListReply>
      PARSER = new com.google.protobuf.AbstractParser<ShoppingCartListReply>() {
    public ShoppingCartListReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ShoppingCartListReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ShoppingCartListReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ShoppingCartListReply> getParserForType() {
    return PARSER;
  }

  public io.reactivesw.shoppingcart.grpc.ShoppingCartListReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

