// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog_proto/catalog_sku_service.proto

package io.reactivesw.catalog.grpc;

public final class CatalogSkuService {
  private CatalogSkuService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'catalog_proto/catalog_sku_service.prot" +
      "o\022$io.reactivesw.catalog.infrastructure\032" +
      ",catalog_proto/google/protobuf/wrappers." +
      "proto\032\'catalog_proto/catalog_sku_message" +
      ".proto2\322\002\n\nSkuService\022M\n\021querySkuInvento" +
      "ry\022\033.google.protobuf.Int64Value\032\033.google" +
      ".protobuf.Int32Value\022n\n\031querySkuSimpleIn" +
      "formation\022\033.google.protobuf.Int64Value\0324" +
      ".io.reactivesw.catalog.infrastructure.Sk" +
      "uInformation\022\204\001\n\027querySkuInformationList",
      "\022/.io.reactivesw.catalog.infrastructure." +
      "SkuIdList\0328.io.reactivesw.catalog.infras" +
      "tructure.SkuInformationListB\036\n\032io.reacti" +
      "vesw.catalog.grpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          io.reactivesw.catalog.grpc.CatalogSkuMessage.getDescriptor(),
        }, assigner);
    com.google.protobuf.WrappersProto.getDescriptor();
    io.reactivesw.catalog.grpc.CatalogSkuMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
