// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog_proto/catalog_message.proto

package io.reactivesw.catalog.grpc;

/**
 * Protobuf type {@code io.reactivesw.catalog.infrastructure.GrpcSku}
 */
public  final class GrpcSku extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.reactivesw.catalog.infrastructure.GrpcSku)
    GrpcSkuOrBuilder {
  // Use GrpcSku.newBuilder() to construct.
  private GrpcSku(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GrpcSku() {
    id_ = 0L;
    skuNumber_ = "";
    isActive_ = false;
    quatity_ = 0;
    upc_ = "";
    displayOrder_ = 0;
    media_ = java.util.Collections.emptyList();
    variantValue_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private GrpcSku(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            skuNumber_ = s;
            break;
          }
          case 24: {

            isActive_ = input.readBool();
            break;
          }
          case 32: {

            quatity_ = input.readInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            upc_ = s;
            break;
          }
          case 48: {

            displayOrder_ = input.readInt32();
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              media_ = new java.util.ArrayList<io.reactivesw.catalog.grpc.GrpcMedia>();
              mutable_bitField0_ |= 0x00000040;
            }
            media_.add(
                input.readMessage(io.reactivesw.catalog.grpc.GrpcMedia.parser(), extensionRegistry));
            break;
          }
          case 66: {
            if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
              variantValue_ = new java.util.ArrayList<io.reactivesw.catalog.grpc.GrpcVariantValue>();
              mutable_bitField0_ |= 0x00000080;
            }
            variantValue_.add(
                input.readMessage(io.reactivesw.catalog.grpc.GrpcVariantValue.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
        media_ = java.util.Collections.unmodifiableList(media_);
      }
      if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
        variantValue_ = java.util.Collections.unmodifiableList(variantValue_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.reactivesw.catalog.grpc.CatalogMessage.internal_static_io_reactivesw_catalog_infrastructure_GrpcSku_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.reactivesw.catalog.grpc.CatalogMessage.internal_static_io_reactivesw_catalog_infrastructure_GrpcSku_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.reactivesw.catalog.grpc.GrpcSku.class, io.reactivesw.catalog.grpc.GrpcSku.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>optional int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int SKUNUMBER_FIELD_NUMBER = 2;
  private volatile java.lang.Object skuNumber_;
  /**
   * <code>optional string skuNumber = 2;</code>
   */
  public java.lang.String getSkuNumber() {
    java.lang.Object ref = skuNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      skuNumber_ = s;
      return s;
    }
  }
  /**
   * <code>optional string skuNumber = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSkuNumberBytes() {
    java.lang.Object ref = skuNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      skuNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISACTIVE_FIELD_NUMBER = 3;
  private boolean isActive_;
  /**
   * <code>optional bool isActive = 3;</code>
   */
  public boolean getIsActive() {
    return isActive_;
  }

  public static final int QUATITY_FIELD_NUMBER = 4;
  private int quatity_;
  /**
   * <code>optional int32 quatity = 4;</code>
   */
  public int getQuatity() {
    return quatity_;
  }

  public static final int UPC_FIELD_NUMBER = 5;
  private volatile java.lang.Object upc_;
  /**
   * <code>optional string upc = 5;</code>
   */
  public java.lang.String getUpc() {
    java.lang.Object ref = upc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      upc_ = s;
      return s;
    }
  }
  /**
   * <code>optional string upc = 5;</code>
   */
  public com.google.protobuf.ByteString
      getUpcBytes() {
    java.lang.Object ref = upc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      upc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAY_ORDER_FIELD_NUMBER = 6;
  private int displayOrder_;
  /**
   * <code>optional int32 display_order = 6;</code>
   */
  public int getDisplayOrder() {
    return displayOrder_;
  }

  public static final int MEDIA_FIELD_NUMBER = 7;
  private java.util.List<io.reactivesw.catalog.grpc.GrpcMedia> media_;
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
   */
  public java.util.List<io.reactivesw.catalog.grpc.GrpcMedia> getMediaList() {
    return media_;
  }
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
   */
  public java.util.List<? extends io.reactivesw.catalog.grpc.GrpcMediaOrBuilder> 
      getMediaOrBuilderList() {
    return media_;
  }
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
   */
  public int getMediaCount() {
    return media_.size();
  }
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
   */
  public io.reactivesw.catalog.grpc.GrpcMedia getMedia(int index) {
    return media_.get(index);
  }
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
   */
  public io.reactivesw.catalog.grpc.GrpcMediaOrBuilder getMediaOrBuilder(
      int index) {
    return media_.get(index);
  }

  public static final int VARIANT_VALUE_FIELD_NUMBER = 8;
  private java.util.List<io.reactivesw.catalog.grpc.GrpcVariantValue> variantValue_;
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
   */
  public java.util.List<io.reactivesw.catalog.grpc.GrpcVariantValue> getVariantValueList() {
    return variantValue_;
  }
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
   */
  public java.util.List<? extends io.reactivesw.catalog.grpc.GrpcVariantValueOrBuilder> 
      getVariantValueOrBuilderList() {
    return variantValue_;
  }
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
   */
  public int getVariantValueCount() {
    return variantValue_.size();
  }
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
   */
  public io.reactivesw.catalog.grpc.GrpcVariantValue getVariantValue(int index) {
    return variantValue_.get(index);
  }
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
   */
  public io.reactivesw.catalog.grpc.GrpcVariantValueOrBuilder getVariantValueOrBuilder(
      int index) {
    return variantValue_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!getSkuNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, skuNumber_);
    }
    if (isActive_ != false) {
      output.writeBool(3, isActive_);
    }
    if (quatity_ != 0) {
      output.writeInt32(4, quatity_);
    }
    if (!getUpcBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, upc_);
    }
    if (displayOrder_ != 0) {
      output.writeInt32(6, displayOrder_);
    }
    for (int i = 0; i < media_.size(); i++) {
      output.writeMessage(7, media_.get(i));
    }
    for (int i = 0; i < variantValue_.size(); i++) {
      output.writeMessage(8, variantValue_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!getSkuNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, skuNumber_);
    }
    if (isActive_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, isActive_);
    }
    if (quatity_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, quatity_);
    }
    if (!getUpcBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, upc_);
    }
    if (displayOrder_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, displayOrder_);
    }
    for (int i = 0; i < media_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, media_.get(i));
    }
    for (int i = 0; i < variantValue_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, variantValue_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.reactivesw.catalog.grpc.GrpcSku)) {
      return super.equals(obj);
    }
    io.reactivesw.catalog.grpc.GrpcSku other = (io.reactivesw.catalog.grpc.GrpcSku) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getSkuNumber()
        .equals(other.getSkuNumber());
    result = result && (getIsActive()
        == other.getIsActive());
    result = result && (getQuatity()
        == other.getQuatity());
    result = result && getUpc()
        .equals(other.getUpc());
    result = result && (getDisplayOrder()
        == other.getDisplayOrder());
    result = result && getMediaList()
        .equals(other.getMediaList());
    result = result && getVariantValueList()
        .equals(other.getVariantValueList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + SKUNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getSkuNumber().hashCode();
    hash = (37 * hash) + ISACTIVE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsActive());
    hash = (37 * hash) + QUATITY_FIELD_NUMBER;
    hash = (53 * hash) + getQuatity();
    hash = (37 * hash) + UPC_FIELD_NUMBER;
    hash = (53 * hash) + getUpc().hashCode();
    hash = (37 * hash) + DISPLAY_ORDER_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayOrder();
    if (getMediaCount() > 0) {
      hash = (37 * hash) + MEDIA_FIELD_NUMBER;
      hash = (53 * hash) + getMediaList().hashCode();
    }
    if (getVariantValueCount() > 0) {
      hash = (37 * hash) + VARIANT_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getVariantValueList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.reactivesw.catalog.grpc.GrpcSku parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.reactivesw.catalog.grpc.GrpcSku parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.reactivesw.catalog.grpc.GrpcSku parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.reactivesw.catalog.grpc.GrpcSku parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.reactivesw.catalog.grpc.GrpcSku parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.reactivesw.catalog.grpc.GrpcSku parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.reactivesw.catalog.grpc.GrpcSku parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.reactivesw.catalog.grpc.GrpcSku parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.reactivesw.catalog.grpc.GrpcSku parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.reactivesw.catalog.grpc.GrpcSku parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.reactivesw.catalog.grpc.GrpcSku prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.reactivesw.catalog.infrastructure.GrpcSku}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.reactivesw.catalog.infrastructure.GrpcSku)
      io.reactivesw.catalog.grpc.GrpcSkuOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.reactivesw.catalog.grpc.CatalogMessage.internal_static_io_reactivesw_catalog_infrastructure_GrpcSku_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.reactivesw.catalog.grpc.CatalogMessage.internal_static_io_reactivesw_catalog_infrastructure_GrpcSku_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.reactivesw.catalog.grpc.GrpcSku.class, io.reactivesw.catalog.grpc.GrpcSku.Builder.class);
    }

    // Construct using io.reactivesw.catalog.grpc.GrpcSku.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMediaFieldBuilder();
        getVariantValueFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0L;

      skuNumber_ = "";

      isActive_ = false;

      quatity_ = 0;

      upc_ = "";

      displayOrder_ = 0;

      if (mediaBuilder_ == null) {
        media_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
      } else {
        mediaBuilder_.clear();
      }
      if (variantValueBuilder_ == null) {
        variantValue_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
      } else {
        variantValueBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.reactivesw.catalog.grpc.CatalogMessage.internal_static_io_reactivesw_catalog_infrastructure_GrpcSku_descriptor;
    }

    public io.reactivesw.catalog.grpc.GrpcSku getDefaultInstanceForType() {
      return io.reactivesw.catalog.grpc.GrpcSku.getDefaultInstance();
    }

    public io.reactivesw.catalog.grpc.GrpcSku build() {
      io.reactivesw.catalog.grpc.GrpcSku result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.reactivesw.catalog.grpc.GrpcSku buildPartial() {
      io.reactivesw.catalog.grpc.GrpcSku result = new io.reactivesw.catalog.grpc.GrpcSku(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.skuNumber_ = skuNumber_;
      result.isActive_ = isActive_;
      result.quatity_ = quatity_;
      result.upc_ = upc_;
      result.displayOrder_ = displayOrder_;
      if (mediaBuilder_ == null) {
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          media_ = java.util.Collections.unmodifiableList(media_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.media_ = media_;
      } else {
        result.media_ = mediaBuilder_.build();
      }
      if (variantValueBuilder_ == null) {
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          variantValue_ = java.util.Collections.unmodifiableList(variantValue_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.variantValue_ = variantValue_;
      } else {
        result.variantValue_ = variantValueBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.reactivesw.catalog.grpc.GrpcSku) {
        return mergeFrom((io.reactivesw.catalog.grpc.GrpcSku)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.reactivesw.catalog.grpc.GrpcSku other) {
      if (other == io.reactivesw.catalog.grpc.GrpcSku.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getSkuNumber().isEmpty()) {
        skuNumber_ = other.skuNumber_;
        onChanged();
      }
      if (other.getIsActive() != false) {
        setIsActive(other.getIsActive());
      }
      if (other.getQuatity() != 0) {
        setQuatity(other.getQuatity());
      }
      if (!other.getUpc().isEmpty()) {
        upc_ = other.upc_;
        onChanged();
      }
      if (other.getDisplayOrder() != 0) {
        setDisplayOrder(other.getDisplayOrder());
      }
      if (mediaBuilder_ == null) {
        if (!other.media_.isEmpty()) {
          if (media_.isEmpty()) {
            media_ = other.media_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureMediaIsMutable();
            media_.addAll(other.media_);
          }
          onChanged();
        }
      } else {
        if (!other.media_.isEmpty()) {
          if (mediaBuilder_.isEmpty()) {
            mediaBuilder_.dispose();
            mediaBuilder_ = null;
            media_ = other.media_;
            bitField0_ = (bitField0_ & ~0x00000040);
            mediaBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMediaFieldBuilder() : null;
          } else {
            mediaBuilder_.addAllMessages(other.media_);
          }
        }
      }
      if (variantValueBuilder_ == null) {
        if (!other.variantValue_.isEmpty()) {
          if (variantValue_.isEmpty()) {
            variantValue_ = other.variantValue_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureVariantValueIsMutable();
            variantValue_.addAll(other.variantValue_);
          }
          onChanged();
        }
      } else {
        if (!other.variantValue_.isEmpty()) {
          if (variantValueBuilder_.isEmpty()) {
            variantValueBuilder_.dispose();
            variantValueBuilder_ = null;
            variantValue_ = other.variantValue_;
            bitField0_ = (bitField0_ & ~0x00000080);
            variantValueBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVariantValueFieldBuilder() : null;
          } else {
            variantValueBuilder_.addAllMessages(other.variantValue_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.reactivesw.catalog.grpc.GrpcSku parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.reactivesw.catalog.grpc.GrpcSku) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>optional int64 id = 1;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object skuNumber_ = "";
    /**
     * <code>optional string skuNumber = 2;</code>
     */
    public java.lang.String getSkuNumber() {
      java.lang.Object ref = skuNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        skuNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string skuNumber = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSkuNumberBytes() {
      java.lang.Object ref = skuNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        skuNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string skuNumber = 2;</code>
     */
    public Builder setSkuNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      skuNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string skuNumber = 2;</code>
     */
    public Builder clearSkuNumber() {
      
      skuNumber_ = getDefaultInstance().getSkuNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional string skuNumber = 2;</code>
     */
    public Builder setSkuNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      skuNumber_ = value;
      onChanged();
      return this;
    }

    private boolean isActive_ ;
    /**
     * <code>optional bool isActive = 3;</code>
     */
    public boolean getIsActive() {
      return isActive_;
    }
    /**
     * <code>optional bool isActive = 3;</code>
     */
    public Builder setIsActive(boolean value) {
      
      isActive_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool isActive = 3;</code>
     */
    public Builder clearIsActive() {
      
      isActive_ = false;
      onChanged();
      return this;
    }

    private int quatity_ ;
    /**
     * <code>optional int32 quatity = 4;</code>
     */
    public int getQuatity() {
      return quatity_;
    }
    /**
     * <code>optional int32 quatity = 4;</code>
     */
    public Builder setQuatity(int value) {
      
      quatity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 quatity = 4;</code>
     */
    public Builder clearQuatity() {
      
      quatity_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object upc_ = "";
    /**
     * <code>optional string upc = 5;</code>
     */
    public java.lang.String getUpc() {
      java.lang.Object ref = upc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        upc_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string upc = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUpcBytes() {
      java.lang.Object ref = upc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        upc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string upc = 5;</code>
     */
    public Builder setUpc(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      upc_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string upc = 5;</code>
     */
    public Builder clearUpc() {
      
      upc_ = getDefaultInstance().getUpc();
      onChanged();
      return this;
    }
    /**
     * <code>optional string upc = 5;</code>
     */
    public Builder setUpcBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      upc_ = value;
      onChanged();
      return this;
    }

    private int displayOrder_ ;
    /**
     * <code>optional int32 display_order = 6;</code>
     */
    public int getDisplayOrder() {
      return displayOrder_;
    }
    /**
     * <code>optional int32 display_order = 6;</code>
     */
    public Builder setDisplayOrder(int value) {
      
      displayOrder_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 display_order = 6;</code>
     */
    public Builder clearDisplayOrder() {
      
      displayOrder_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<io.reactivesw.catalog.grpc.GrpcMedia> media_ =
      java.util.Collections.emptyList();
    private void ensureMediaIsMutable() {
      if (!((bitField0_ & 0x00000040) == 0x00000040)) {
        media_ = new java.util.ArrayList<io.reactivesw.catalog.grpc.GrpcMedia>(media_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.reactivesw.catalog.grpc.GrpcMedia, io.reactivesw.catalog.grpc.GrpcMedia.Builder, io.reactivesw.catalog.grpc.GrpcMediaOrBuilder> mediaBuilder_;

    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
     */
    public java.util.List<io.reactivesw.catalog.grpc.GrpcMedia> getMediaList() {
      if (mediaBuilder_ == null) {
        return java.util.Collections.unmodifiableList(media_);
      } else {
        return mediaBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
     */
    public int getMediaCount() {
      if (mediaBuilder_ == null) {
        return media_.size();
      } else {
        return mediaBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcMedia getMedia(int index) {
      if (mediaBuilder_ == null) {
        return media_.get(index);
      } else {
        return mediaBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
     */
    public Builder setMedia(
        int index, io.reactivesw.catalog.grpc.GrpcMedia value) {
      if (mediaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMediaIsMutable();
        media_.set(index, value);
        onChanged();
      } else {
        mediaBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
     */
    public Builder setMedia(
        int index, io.reactivesw.catalog.grpc.GrpcMedia.Builder builderForValue) {
      if (mediaBuilder_ == null) {
        ensureMediaIsMutable();
        media_.set(index, builderForValue.build());
        onChanged();
      } else {
        mediaBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
     */
    public Builder addMedia(io.reactivesw.catalog.grpc.GrpcMedia value) {
      if (mediaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMediaIsMutable();
        media_.add(value);
        onChanged();
      } else {
        mediaBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
     */
    public Builder addMedia(
        int index, io.reactivesw.catalog.grpc.GrpcMedia value) {
      if (mediaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMediaIsMutable();
        media_.add(index, value);
        onChanged();
      } else {
        mediaBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
     */
    public Builder addMedia(
        io.reactivesw.catalog.grpc.GrpcMedia.Builder builderForValue) {
      if (mediaBuilder_ == null) {
        ensureMediaIsMutable();
        media_.add(builderForValue.build());
        onChanged();
      } else {
        mediaBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
     */
    public Builder addMedia(
        int index, io.reactivesw.catalog.grpc.GrpcMedia.Builder builderForValue) {
      if (mediaBuilder_ == null) {
        ensureMediaIsMutable();
        media_.add(index, builderForValue.build());
        onChanged();
      } else {
        mediaBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
     */
    public Builder addAllMedia(
        java.lang.Iterable<? extends io.reactivesw.catalog.grpc.GrpcMedia> values) {
      if (mediaBuilder_ == null) {
        ensureMediaIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, media_);
        onChanged();
      } else {
        mediaBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
     */
    public Builder clearMedia() {
      if (mediaBuilder_ == null) {
        media_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        mediaBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
     */
    public Builder removeMedia(int index) {
      if (mediaBuilder_ == null) {
        ensureMediaIsMutable();
        media_.remove(index);
        onChanged();
      } else {
        mediaBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcMedia.Builder getMediaBuilder(
        int index) {
      return getMediaFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcMediaOrBuilder getMediaOrBuilder(
        int index) {
      if (mediaBuilder_ == null) {
        return media_.get(index);  } else {
        return mediaBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
     */
    public java.util.List<? extends io.reactivesw.catalog.grpc.GrpcMediaOrBuilder> 
         getMediaOrBuilderList() {
      if (mediaBuilder_ != null) {
        return mediaBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(media_);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcMedia.Builder addMediaBuilder() {
      return getMediaFieldBuilder().addBuilder(
          io.reactivesw.catalog.grpc.GrpcMedia.getDefaultInstance());
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcMedia.Builder addMediaBuilder(
        int index) {
      return getMediaFieldBuilder().addBuilder(
          index, io.reactivesw.catalog.grpc.GrpcMedia.getDefaultInstance());
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
     */
    public java.util.List<io.reactivesw.catalog.grpc.GrpcMedia.Builder> 
         getMediaBuilderList() {
      return getMediaFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.reactivesw.catalog.grpc.GrpcMedia, io.reactivesw.catalog.grpc.GrpcMedia.Builder, io.reactivesw.catalog.grpc.GrpcMediaOrBuilder> 
        getMediaFieldBuilder() {
      if (mediaBuilder_ == null) {
        mediaBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.reactivesw.catalog.grpc.GrpcMedia, io.reactivesw.catalog.grpc.GrpcMedia.Builder, io.reactivesw.catalog.grpc.GrpcMediaOrBuilder>(
                media_,
                ((bitField0_ & 0x00000040) == 0x00000040),
                getParentForChildren(),
                isClean());
        media_ = null;
      }
      return mediaBuilder_;
    }

    private java.util.List<io.reactivesw.catalog.grpc.GrpcVariantValue> variantValue_ =
      java.util.Collections.emptyList();
    private void ensureVariantValueIsMutable() {
      if (!((bitField0_ & 0x00000080) == 0x00000080)) {
        variantValue_ = new java.util.ArrayList<io.reactivesw.catalog.grpc.GrpcVariantValue>(variantValue_);
        bitField0_ |= 0x00000080;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.reactivesw.catalog.grpc.GrpcVariantValue, io.reactivesw.catalog.grpc.GrpcVariantValue.Builder, io.reactivesw.catalog.grpc.GrpcVariantValueOrBuilder> variantValueBuilder_;

    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
     */
    public java.util.List<io.reactivesw.catalog.grpc.GrpcVariantValue> getVariantValueList() {
      if (variantValueBuilder_ == null) {
        return java.util.Collections.unmodifiableList(variantValue_);
      } else {
        return variantValueBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
     */
    public int getVariantValueCount() {
      if (variantValueBuilder_ == null) {
        return variantValue_.size();
      } else {
        return variantValueBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcVariantValue getVariantValue(int index) {
      if (variantValueBuilder_ == null) {
        return variantValue_.get(index);
      } else {
        return variantValueBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
     */
    public Builder setVariantValue(
        int index, io.reactivesw.catalog.grpc.GrpcVariantValue value) {
      if (variantValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariantValueIsMutable();
        variantValue_.set(index, value);
        onChanged();
      } else {
        variantValueBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
     */
    public Builder setVariantValue(
        int index, io.reactivesw.catalog.grpc.GrpcVariantValue.Builder builderForValue) {
      if (variantValueBuilder_ == null) {
        ensureVariantValueIsMutable();
        variantValue_.set(index, builderForValue.build());
        onChanged();
      } else {
        variantValueBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
     */
    public Builder addVariantValue(io.reactivesw.catalog.grpc.GrpcVariantValue value) {
      if (variantValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariantValueIsMutable();
        variantValue_.add(value);
        onChanged();
      } else {
        variantValueBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
     */
    public Builder addVariantValue(
        int index, io.reactivesw.catalog.grpc.GrpcVariantValue value) {
      if (variantValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariantValueIsMutable();
        variantValue_.add(index, value);
        onChanged();
      } else {
        variantValueBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
     */
    public Builder addVariantValue(
        io.reactivesw.catalog.grpc.GrpcVariantValue.Builder builderForValue) {
      if (variantValueBuilder_ == null) {
        ensureVariantValueIsMutable();
        variantValue_.add(builderForValue.build());
        onChanged();
      } else {
        variantValueBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
     */
    public Builder addVariantValue(
        int index, io.reactivesw.catalog.grpc.GrpcVariantValue.Builder builderForValue) {
      if (variantValueBuilder_ == null) {
        ensureVariantValueIsMutable();
        variantValue_.add(index, builderForValue.build());
        onChanged();
      } else {
        variantValueBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
     */
    public Builder addAllVariantValue(
        java.lang.Iterable<? extends io.reactivesw.catalog.grpc.GrpcVariantValue> values) {
      if (variantValueBuilder_ == null) {
        ensureVariantValueIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, variantValue_);
        onChanged();
      } else {
        variantValueBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
     */
    public Builder clearVariantValue() {
      if (variantValueBuilder_ == null) {
        variantValue_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
      } else {
        variantValueBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
     */
    public Builder removeVariantValue(int index) {
      if (variantValueBuilder_ == null) {
        ensureVariantValueIsMutable();
        variantValue_.remove(index);
        onChanged();
      } else {
        variantValueBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcVariantValue.Builder getVariantValueBuilder(
        int index) {
      return getVariantValueFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcVariantValueOrBuilder getVariantValueOrBuilder(
        int index) {
      if (variantValueBuilder_ == null) {
        return variantValue_.get(index);  } else {
        return variantValueBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
     */
    public java.util.List<? extends io.reactivesw.catalog.grpc.GrpcVariantValueOrBuilder> 
         getVariantValueOrBuilderList() {
      if (variantValueBuilder_ != null) {
        return variantValueBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(variantValue_);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcVariantValue.Builder addVariantValueBuilder() {
      return getVariantValueFieldBuilder().addBuilder(
          io.reactivesw.catalog.grpc.GrpcVariantValue.getDefaultInstance());
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcVariantValue.Builder addVariantValueBuilder(
        int index) {
      return getVariantValueFieldBuilder().addBuilder(
          index, io.reactivesw.catalog.grpc.GrpcVariantValue.getDefaultInstance());
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
     */
    public java.util.List<io.reactivesw.catalog.grpc.GrpcVariantValue.Builder> 
         getVariantValueBuilderList() {
      return getVariantValueFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.reactivesw.catalog.grpc.GrpcVariantValue, io.reactivesw.catalog.grpc.GrpcVariantValue.Builder, io.reactivesw.catalog.grpc.GrpcVariantValueOrBuilder> 
        getVariantValueFieldBuilder() {
      if (variantValueBuilder_ == null) {
        variantValueBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.reactivesw.catalog.grpc.GrpcVariantValue, io.reactivesw.catalog.grpc.GrpcVariantValue.Builder, io.reactivesw.catalog.grpc.GrpcVariantValueOrBuilder>(
                variantValue_,
                ((bitField0_ & 0x00000080) == 0x00000080),
                getParentForChildren(),
                isClean());
        variantValue_ = null;
      }
      return variantValueBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:io.reactivesw.catalog.infrastructure.GrpcSku)
  }

  // @@protoc_insertion_point(class_scope:io.reactivesw.catalog.infrastructure.GrpcSku)
  private static final io.reactivesw.catalog.grpc.GrpcSku DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.reactivesw.catalog.grpc.GrpcSku();
  }

  public static io.reactivesw.catalog.grpc.GrpcSku getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GrpcSku>
      PARSER = new com.google.protobuf.AbstractParser<GrpcSku>() {
    public GrpcSku parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new GrpcSku(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GrpcSku> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GrpcSku> getParserForType() {
    return PARSER;
  }

  public io.reactivesw.catalog.grpc.GrpcSku getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

