// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog_proto/catalog_message.proto

package io.reactivesw.catalog.grpc;

/**
 * Protobuf type {@code io.reactivesw.catalog.infrastructure.GrpcProduct}
 */
public  final class GrpcProduct extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.reactivesw.catalog.infrastructure.GrpcProduct)
    GrpcProductOrBuilder {
  // Use GrpcProduct.newBuilder() to construct.
  private GrpcProduct(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GrpcProduct() {
    id_ = 0L;
    manufacturer_ = "";
    brand_ = "";
    model_ = "";
    name_ = "";
    price_ = "";
    displayOrder_ = 0;
    description_ = "";
    detail_ = "";
    displayed_ = false;
    deleted_ = false;
    attribute_ = java.util.Collections.emptyList();
    sku_ = java.util.Collections.emptyList();
    variant_ = java.util.Collections.emptyList();
    feature_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private GrpcProduct(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            manufacturer_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            brand_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            model_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            price_ = s;
            break;
          }
          case 56: {

            displayOrder_ = input.readInt32();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            detail_ = s;
            break;
          }
          case 80: {

            displayed_ = input.readBool();
            break;
          }
          case 88: {

            deleted_ = input.readBool();
            break;
          }
          case 98: {
            if (!((mutable_bitField0_ & 0x00000800) == 0x00000800)) {
              attribute_ = new java.util.ArrayList<io.reactivesw.catalog.grpc.GrpcAttribute>();
              mutable_bitField0_ |= 0x00000800;
            }
            attribute_.add(
                input.readMessage(io.reactivesw.catalog.grpc.GrpcAttribute.parser(), extensionRegistry));
            break;
          }
          case 106: {
            if (!((mutable_bitField0_ & 0x00001000) == 0x00001000)) {
              sku_ = new java.util.ArrayList<io.reactivesw.catalog.grpc.GrpcSku>();
              mutable_bitField0_ |= 0x00001000;
            }
            sku_.add(
                input.readMessage(io.reactivesw.catalog.grpc.GrpcSku.parser(), extensionRegistry));
            break;
          }
          case 114: {
            if (!((mutable_bitField0_ & 0x00002000) == 0x00002000)) {
              variant_ = new java.util.ArrayList<io.reactivesw.catalog.grpc.GrpcVariant>();
              mutable_bitField0_ |= 0x00002000;
            }
            variant_.add(
                input.readMessage(io.reactivesw.catalog.grpc.GrpcVariant.parser(), extensionRegistry));
            break;
          }
          case 122: {
            if (!((mutable_bitField0_ & 0x00004000) == 0x00004000)) {
              feature_ = new java.util.ArrayList<io.reactivesw.catalog.grpc.GrpcFeature>();
              mutable_bitField0_ |= 0x00004000;
            }
            feature_.add(
                input.readMessage(io.reactivesw.catalog.grpc.GrpcFeature.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000800) == 0x00000800)) {
        attribute_ = java.util.Collections.unmodifiableList(attribute_);
      }
      if (((mutable_bitField0_ & 0x00001000) == 0x00001000)) {
        sku_ = java.util.Collections.unmodifiableList(sku_);
      }
      if (((mutable_bitField0_ & 0x00002000) == 0x00002000)) {
        variant_ = java.util.Collections.unmodifiableList(variant_);
      }
      if (((mutable_bitField0_ & 0x00004000) == 0x00004000)) {
        feature_ = java.util.Collections.unmodifiableList(feature_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.reactivesw.catalog.grpc.CatalogMessage.internal_static_io_reactivesw_catalog_infrastructure_GrpcProduct_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.reactivesw.catalog.grpc.CatalogMessage.internal_static_io_reactivesw_catalog_infrastructure_GrpcProduct_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.reactivesw.catalog.grpc.GrpcProduct.class, io.reactivesw.catalog.grpc.GrpcProduct.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>optional int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int MANUFACTURER_FIELD_NUMBER = 2;
  private volatile java.lang.Object manufacturer_;
  /**
   * <code>optional string manufacturer = 2;</code>
   */
  public java.lang.String getManufacturer() {
    java.lang.Object ref = manufacturer_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      manufacturer_ = s;
      return s;
    }
  }
  /**
   * <code>optional string manufacturer = 2;</code>
   */
  public com.google.protobuf.ByteString
      getManufacturerBytes() {
    java.lang.Object ref = manufacturer_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      manufacturer_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BRAND_FIELD_NUMBER = 3;
  private volatile java.lang.Object brand_;
  /**
   * <code>optional string brand = 3;</code>
   */
  public java.lang.String getBrand() {
    java.lang.Object ref = brand_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      brand_ = s;
      return s;
    }
  }
  /**
   * <code>optional string brand = 3;</code>
   */
  public com.google.protobuf.ByteString
      getBrandBytes() {
    java.lang.Object ref = brand_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      brand_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODEL_FIELD_NUMBER = 4;
  private volatile java.lang.Object model_;
  /**
   * <code>optional string model = 4;</code>
   */
  public java.lang.String getModel() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      model_ = s;
      return s;
    }
  }
  /**
   * <code>optional string model = 4;</code>
   */
  public com.google.protobuf.ByteString
      getModelBytes() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      model_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 5;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string name = 5;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>optional string name = 5;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRICE_FIELD_NUMBER = 6;
  private volatile java.lang.Object price_;
  /**
   * <code>optional string price = 6;</code>
   */
  public java.lang.String getPrice() {
    java.lang.Object ref = price_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      price_ = s;
      return s;
    }
  }
  /**
   * <code>optional string price = 6;</code>
   */
  public com.google.protobuf.ByteString
      getPriceBytes() {
    java.lang.Object ref = price_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      price_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAY_ORDER_FIELD_NUMBER = 7;
  private int displayOrder_;
  /**
   * <code>optional int32 display_order = 7;</code>
   */
  public int getDisplayOrder() {
    return displayOrder_;
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 8;
  private volatile java.lang.Object description_;
  /**
   * <code>optional string description = 8;</code>
   */
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>optional string description = 8;</code>
   */
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DETAIL_FIELD_NUMBER = 9;
  private volatile java.lang.Object detail_;
  /**
   * <code>optional string detail = 9;</code>
   */
  public java.lang.String getDetail() {
    java.lang.Object ref = detail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      detail_ = s;
      return s;
    }
  }
  /**
   * <code>optional string detail = 9;</code>
   */
  public com.google.protobuf.ByteString
      getDetailBytes() {
    java.lang.Object ref = detail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      detail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DISPLAYED_FIELD_NUMBER = 10;
  private boolean displayed_;
  /**
   * <code>optional bool displayed = 10;</code>
   */
  public boolean getDisplayed() {
    return displayed_;
  }

  public static final int DELETED_FIELD_NUMBER = 11;
  private boolean deleted_;
  /**
   * <code>optional bool deleted = 11;</code>
   */
  public boolean getDeleted() {
    return deleted_;
  }

  public static final int ATTRIBUTE_FIELD_NUMBER = 12;
  private java.util.List<io.reactivesw.catalog.grpc.GrpcAttribute> attribute_;
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
   */
  public java.util.List<io.reactivesw.catalog.grpc.GrpcAttribute> getAttributeList() {
    return attribute_;
  }
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
   */
  public java.util.List<? extends io.reactivesw.catalog.grpc.GrpcAttributeOrBuilder> 
      getAttributeOrBuilderList() {
    return attribute_;
  }
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
   */
  public int getAttributeCount() {
    return attribute_.size();
  }
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
   */
  public io.reactivesw.catalog.grpc.GrpcAttribute getAttribute(int index) {
    return attribute_.get(index);
  }
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
   */
  public io.reactivesw.catalog.grpc.GrpcAttributeOrBuilder getAttributeOrBuilder(
      int index) {
    return attribute_.get(index);
  }

  public static final int SKU_FIELD_NUMBER = 13;
  private java.util.List<io.reactivesw.catalog.grpc.GrpcSku> sku_;
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
   */
  public java.util.List<io.reactivesw.catalog.grpc.GrpcSku> getSkuList() {
    return sku_;
  }
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
   */
  public java.util.List<? extends io.reactivesw.catalog.grpc.GrpcSkuOrBuilder> 
      getSkuOrBuilderList() {
    return sku_;
  }
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
   */
  public int getSkuCount() {
    return sku_.size();
  }
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
   */
  public io.reactivesw.catalog.grpc.GrpcSku getSku(int index) {
    return sku_.get(index);
  }
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
   */
  public io.reactivesw.catalog.grpc.GrpcSkuOrBuilder getSkuOrBuilder(
      int index) {
    return sku_.get(index);
  }

  public static final int VARIANT_FIELD_NUMBER = 14;
  private java.util.List<io.reactivesw.catalog.grpc.GrpcVariant> variant_;
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
   */
  public java.util.List<io.reactivesw.catalog.grpc.GrpcVariant> getVariantList() {
    return variant_;
  }
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
   */
  public java.util.List<? extends io.reactivesw.catalog.grpc.GrpcVariantOrBuilder> 
      getVariantOrBuilderList() {
    return variant_;
  }
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
   */
  public int getVariantCount() {
    return variant_.size();
  }
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
   */
  public io.reactivesw.catalog.grpc.GrpcVariant getVariant(int index) {
    return variant_.get(index);
  }
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
   */
  public io.reactivesw.catalog.grpc.GrpcVariantOrBuilder getVariantOrBuilder(
      int index) {
    return variant_.get(index);
  }

  public static final int FEATURE_FIELD_NUMBER = 15;
  private java.util.List<io.reactivesw.catalog.grpc.GrpcFeature> feature_;
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
   */
  public java.util.List<io.reactivesw.catalog.grpc.GrpcFeature> getFeatureList() {
    return feature_;
  }
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
   */
  public java.util.List<? extends io.reactivesw.catalog.grpc.GrpcFeatureOrBuilder> 
      getFeatureOrBuilderList() {
    return feature_;
  }
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
   */
  public int getFeatureCount() {
    return feature_.size();
  }
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
   */
  public io.reactivesw.catalog.grpc.GrpcFeature getFeature(int index) {
    return feature_.get(index);
  }
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
   */
  public io.reactivesw.catalog.grpc.GrpcFeatureOrBuilder getFeatureOrBuilder(
      int index) {
    return feature_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!getManufacturerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, manufacturer_);
    }
    if (!getBrandBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, brand_);
    }
    if (!getModelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, model_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, name_);
    }
    if (!getPriceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, price_);
    }
    if (displayOrder_ != 0) {
      output.writeInt32(7, displayOrder_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, description_);
    }
    if (!getDetailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, detail_);
    }
    if (displayed_ != false) {
      output.writeBool(10, displayed_);
    }
    if (deleted_ != false) {
      output.writeBool(11, deleted_);
    }
    for (int i = 0; i < attribute_.size(); i++) {
      output.writeMessage(12, attribute_.get(i));
    }
    for (int i = 0; i < sku_.size(); i++) {
      output.writeMessage(13, sku_.get(i));
    }
    for (int i = 0; i < variant_.size(); i++) {
      output.writeMessage(14, variant_.get(i));
    }
    for (int i = 0; i < feature_.size(); i++) {
      output.writeMessage(15, feature_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!getManufacturerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, manufacturer_);
    }
    if (!getBrandBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, brand_);
    }
    if (!getModelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, model_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, name_);
    }
    if (!getPriceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, price_);
    }
    if (displayOrder_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, displayOrder_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, description_);
    }
    if (!getDetailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, detail_);
    }
    if (displayed_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, displayed_);
    }
    if (deleted_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(11, deleted_);
    }
    for (int i = 0; i < attribute_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, attribute_.get(i));
    }
    for (int i = 0; i < sku_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, sku_.get(i));
    }
    for (int i = 0; i < variant_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(14, variant_.get(i));
    }
    for (int i = 0; i < feature_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(15, feature_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.reactivesw.catalog.grpc.GrpcProduct)) {
      return super.equals(obj);
    }
    io.reactivesw.catalog.grpc.GrpcProduct other = (io.reactivesw.catalog.grpc.GrpcProduct) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getManufacturer()
        .equals(other.getManufacturer());
    result = result && getBrand()
        .equals(other.getBrand());
    result = result && getModel()
        .equals(other.getModel());
    result = result && getName()
        .equals(other.getName());
    result = result && getPrice()
        .equals(other.getPrice());
    result = result && (getDisplayOrder()
        == other.getDisplayOrder());
    result = result && getDescription()
        .equals(other.getDescription());
    result = result && getDetail()
        .equals(other.getDetail());
    result = result && (getDisplayed()
        == other.getDisplayed());
    result = result && (getDeleted()
        == other.getDeleted());
    result = result && getAttributeList()
        .equals(other.getAttributeList());
    result = result && getSkuList()
        .equals(other.getSkuList());
    result = result && getVariantList()
        .equals(other.getVariantList());
    result = result && getFeatureList()
        .equals(other.getFeatureList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + MANUFACTURER_FIELD_NUMBER;
    hash = (53 * hash) + getManufacturer().hashCode();
    hash = (37 * hash) + BRAND_FIELD_NUMBER;
    hash = (53 * hash) + getBrand().hashCode();
    hash = (37 * hash) + MODEL_FIELD_NUMBER;
    hash = (53 * hash) + getModel().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + getPrice().hashCode();
    hash = (37 * hash) + DISPLAY_ORDER_FIELD_NUMBER;
    hash = (53 * hash) + getDisplayOrder();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + DETAIL_FIELD_NUMBER;
    hash = (53 * hash) + getDetail().hashCode();
    hash = (37 * hash) + DISPLAYED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDisplayed());
    hash = (37 * hash) + DELETED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDeleted());
    if (getAttributeCount() > 0) {
      hash = (37 * hash) + ATTRIBUTE_FIELD_NUMBER;
      hash = (53 * hash) + getAttributeList().hashCode();
    }
    if (getSkuCount() > 0) {
      hash = (37 * hash) + SKU_FIELD_NUMBER;
      hash = (53 * hash) + getSkuList().hashCode();
    }
    if (getVariantCount() > 0) {
      hash = (37 * hash) + VARIANT_FIELD_NUMBER;
      hash = (53 * hash) + getVariantList().hashCode();
    }
    if (getFeatureCount() > 0) {
      hash = (37 * hash) + FEATURE_FIELD_NUMBER;
      hash = (53 * hash) + getFeatureList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.reactivesw.catalog.grpc.GrpcProduct parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.reactivesw.catalog.grpc.GrpcProduct parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.reactivesw.catalog.grpc.GrpcProduct parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.reactivesw.catalog.grpc.GrpcProduct parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.reactivesw.catalog.grpc.GrpcProduct parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.reactivesw.catalog.grpc.GrpcProduct parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.reactivesw.catalog.grpc.GrpcProduct parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.reactivesw.catalog.grpc.GrpcProduct parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.reactivesw.catalog.grpc.GrpcProduct parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.reactivesw.catalog.grpc.GrpcProduct parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.reactivesw.catalog.grpc.GrpcProduct prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.reactivesw.catalog.infrastructure.GrpcProduct}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.reactivesw.catalog.infrastructure.GrpcProduct)
      io.reactivesw.catalog.grpc.GrpcProductOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.reactivesw.catalog.grpc.CatalogMessage.internal_static_io_reactivesw_catalog_infrastructure_GrpcProduct_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.reactivesw.catalog.grpc.CatalogMessage.internal_static_io_reactivesw_catalog_infrastructure_GrpcProduct_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.reactivesw.catalog.grpc.GrpcProduct.class, io.reactivesw.catalog.grpc.GrpcProduct.Builder.class);
    }

    // Construct using io.reactivesw.catalog.grpc.GrpcProduct.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAttributeFieldBuilder();
        getSkuFieldBuilder();
        getVariantFieldBuilder();
        getFeatureFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0L;

      manufacturer_ = "";

      brand_ = "";

      model_ = "";

      name_ = "";

      price_ = "";

      displayOrder_ = 0;

      description_ = "";

      detail_ = "";

      displayed_ = false;

      deleted_ = false;

      if (attributeBuilder_ == null) {
        attribute_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000800);
      } else {
        attributeBuilder_.clear();
      }
      if (skuBuilder_ == null) {
        sku_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00001000);
      } else {
        skuBuilder_.clear();
      }
      if (variantBuilder_ == null) {
        variant_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00002000);
      } else {
        variantBuilder_.clear();
      }
      if (featureBuilder_ == null) {
        feature_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00004000);
      } else {
        featureBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.reactivesw.catalog.grpc.CatalogMessage.internal_static_io_reactivesw_catalog_infrastructure_GrpcProduct_descriptor;
    }

    public io.reactivesw.catalog.grpc.GrpcProduct getDefaultInstanceForType() {
      return io.reactivesw.catalog.grpc.GrpcProduct.getDefaultInstance();
    }

    public io.reactivesw.catalog.grpc.GrpcProduct build() {
      io.reactivesw.catalog.grpc.GrpcProduct result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.reactivesw.catalog.grpc.GrpcProduct buildPartial() {
      io.reactivesw.catalog.grpc.GrpcProduct result = new io.reactivesw.catalog.grpc.GrpcProduct(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.manufacturer_ = manufacturer_;
      result.brand_ = brand_;
      result.model_ = model_;
      result.name_ = name_;
      result.price_ = price_;
      result.displayOrder_ = displayOrder_;
      result.description_ = description_;
      result.detail_ = detail_;
      result.displayed_ = displayed_;
      result.deleted_ = deleted_;
      if (attributeBuilder_ == null) {
        if (((bitField0_ & 0x00000800) == 0x00000800)) {
          attribute_ = java.util.Collections.unmodifiableList(attribute_);
          bitField0_ = (bitField0_ & ~0x00000800);
        }
        result.attribute_ = attribute_;
      } else {
        result.attribute_ = attributeBuilder_.build();
      }
      if (skuBuilder_ == null) {
        if (((bitField0_ & 0x00001000) == 0x00001000)) {
          sku_ = java.util.Collections.unmodifiableList(sku_);
          bitField0_ = (bitField0_ & ~0x00001000);
        }
        result.sku_ = sku_;
      } else {
        result.sku_ = skuBuilder_.build();
      }
      if (variantBuilder_ == null) {
        if (((bitField0_ & 0x00002000) == 0x00002000)) {
          variant_ = java.util.Collections.unmodifiableList(variant_);
          bitField0_ = (bitField0_ & ~0x00002000);
        }
        result.variant_ = variant_;
      } else {
        result.variant_ = variantBuilder_.build();
      }
      if (featureBuilder_ == null) {
        if (((bitField0_ & 0x00004000) == 0x00004000)) {
          feature_ = java.util.Collections.unmodifiableList(feature_);
          bitField0_ = (bitField0_ & ~0x00004000);
        }
        result.feature_ = feature_;
      } else {
        result.feature_ = featureBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.reactivesw.catalog.grpc.GrpcProduct) {
        return mergeFrom((io.reactivesw.catalog.grpc.GrpcProduct)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.reactivesw.catalog.grpc.GrpcProduct other) {
      if (other == io.reactivesw.catalog.grpc.GrpcProduct.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getManufacturer().isEmpty()) {
        manufacturer_ = other.manufacturer_;
        onChanged();
      }
      if (!other.getBrand().isEmpty()) {
        brand_ = other.brand_;
        onChanged();
      }
      if (!other.getModel().isEmpty()) {
        model_ = other.model_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getPrice().isEmpty()) {
        price_ = other.price_;
        onChanged();
      }
      if (other.getDisplayOrder() != 0) {
        setDisplayOrder(other.getDisplayOrder());
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (!other.getDetail().isEmpty()) {
        detail_ = other.detail_;
        onChanged();
      }
      if (other.getDisplayed() != false) {
        setDisplayed(other.getDisplayed());
      }
      if (other.getDeleted() != false) {
        setDeleted(other.getDeleted());
      }
      if (attributeBuilder_ == null) {
        if (!other.attribute_.isEmpty()) {
          if (attribute_.isEmpty()) {
            attribute_ = other.attribute_;
            bitField0_ = (bitField0_ & ~0x00000800);
          } else {
            ensureAttributeIsMutable();
            attribute_.addAll(other.attribute_);
          }
          onChanged();
        }
      } else {
        if (!other.attribute_.isEmpty()) {
          if (attributeBuilder_.isEmpty()) {
            attributeBuilder_.dispose();
            attributeBuilder_ = null;
            attribute_ = other.attribute_;
            bitField0_ = (bitField0_ & ~0x00000800);
            attributeBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAttributeFieldBuilder() : null;
          } else {
            attributeBuilder_.addAllMessages(other.attribute_);
          }
        }
      }
      if (skuBuilder_ == null) {
        if (!other.sku_.isEmpty()) {
          if (sku_.isEmpty()) {
            sku_ = other.sku_;
            bitField0_ = (bitField0_ & ~0x00001000);
          } else {
            ensureSkuIsMutable();
            sku_.addAll(other.sku_);
          }
          onChanged();
        }
      } else {
        if (!other.sku_.isEmpty()) {
          if (skuBuilder_.isEmpty()) {
            skuBuilder_.dispose();
            skuBuilder_ = null;
            sku_ = other.sku_;
            bitField0_ = (bitField0_ & ~0x00001000);
            skuBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSkuFieldBuilder() : null;
          } else {
            skuBuilder_.addAllMessages(other.sku_);
          }
        }
      }
      if (variantBuilder_ == null) {
        if (!other.variant_.isEmpty()) {
          if (variant_.isEmpty()) {
            variant_ = other.variant_;
            bitField0_ = (bitField0_ & ~0x00002000);
          } else {
            ensureVariantIsMutable();
            variant_.addAll(other.variant_);
          }
          onChanged();
        }
      } else {
        if (!other.variant_.isEmpty()) {
          if (variantBuilder_.isEmpty()) {
            variantBuilder_.dispose();
            variantBuilder_ = null;
            variant_ = other.variant_;
            bitField0_ = (bitField0_ & ~0x00002000);
            variantBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVariantFieldBuilder() : null;
          } else {
            variantBuilder_.addAllMessages(other.variant_);
          }
        }
      }
      if (featureBuilder_ == null) {
        if (!other.feature_.isEmpty()) {
          if (feature_.isEmpty()) {
            feature_ = other.feature_;
            bitField0_ = (bitField0_ & ~0x00004000);
          } else {
            ensureFeatureIsMutable();
            feature_.addAll(other.feature_);
          }
          onChanged();
        }
      } else {
        if (!other.feature_.isEmpty()) {
          if (featureBuilder_.isEmpty()) {
            featureBuilder_.dispose();
            featureBuilder_ = null;
            feature_ = other.feature_;
            bitField0_ = (bitField0_ & ~0x00004000);
            featureBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFeatureFieldBuilder() : null;
          } else {
            featureBuilder_.addAllMessages(other.feature_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.reactivesw.catalog.grpc.GrpcProduct parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.reactivesw.catalog.grpc.GrpcProduct) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>optional int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>optional int64 id = 1;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object manufacturer_ = "";
    /**
     * <code>optional string manufacturer = 2;</code>
     */
    public java.lang.String getManufacturer() {
      java.lang.Object ref = manufacturer_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        manufacturer_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string manufacturer = 2;</code>
     */
    public com.google.protobuf.ByteString
        getManufacturerBytes() {
      java.lang.Object ref = manufacturer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        manufacturer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string manufacturer = 2;</code>
     */
    public Builder setManufacturer(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      manufacturer_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string manufacturer = 2;</code>
     */
    public Builder clearManufacturer() {
      
      manufacturer_ = getDefaultInstance().getManufacturer();
      onChanged();
      return this;
    }
    /**
     * <code>optional string manufacturer = 2;</code>
     */
    public Builder setManufacturerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      manufacturer_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object brand_ = "";
    /**
     * <code>optional string brand = 3;</code>
     */
    public java.lang.String getBrand() {
      java.lang.Object ref = brand_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        brand_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string brand = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBrandBytes() {
      java.lang.Object ref = brand_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string brand = 3;</code>
     */
    public Builder setBrand(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      brand_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string brand = 3;</code>
     */
    public Builder clearBrand() {
      
      brand_ = getDefaultInstance().getBrand();
      onChanged();
      return this;
    }
    /**
     * <code>optional string brand = 3;</code>
     */
    public Builder setBrandBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      brand_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object model_ = "";
    /**
     * <code>optional string model = 4;</code>
     */
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        model_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string model = 4;</code>
     */
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string model = 4;</code>
     */
    public Builder setModel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      model_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string model = 4;</code>
     */
    public Builder clearModel() {
      
      model_ = getDefaultInstance().getModel();
      onChanged();
      return this;
    }
    /**
     * <code>optional string model = 4;</code>
     */
    public Builder setModelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      model_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 5;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 5;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 5;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 5;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 5;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object price_ = "";
    /**
     * <code>optional string price = 6;</code>
     */
    public java.lang.String getPrice() {
      java.lang.Object ref = price_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        price_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string price = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPriceBytes() {
      java.lang.Object ref = price_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        price_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string price = 6;</code>
     */
    public Builder setPrice(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string price = 6;</code>
     */
    public Builder clearPrice() {
      
      price_ = getDefaultInstance().getPrice();
      onChanged();
      return this;
    }
    /**
     * <code>optional string price = 6;</code>
     */
    public Builder setPriceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      price_ = value;
      onChanged();
      return this;
    }

    private int displayOrder_ ;
    /**
     * <code>optional int32 display_order = 7;</code>
     */
    public int getDisplayOrder() {
      return displayOrder_;
    }
    /**
     * <code>optional int32 display_order = 7;</code>
     */
    public Builder setDisplayOrder(int value) {
      
      displayOrder_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 display_order = 7;</code>
     */
    public Builder clearDisplayOrder() {
      
      displayOrder_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>optional string description = 8;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string description = 8;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string description = 8;</code>
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string description = 8;</code>
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>optional string description = 8;</code>
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object detail_ = "";
    /**
     * <code>optional string detail = 9;</code>
     */
    public java.lang.String getDetail() {
      java.lang.Object ref = detail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        detail_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string detail = 9;</code>
     */
    public com.google.protobuf.ByteString
        getDetailBytes() {
      java.lang.Object ref = detail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        detail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string detail = 9;</code>
     */
    public Builder setDetail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      detail_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string detail = 9;</code>
     */
    public Builder clearDetail() {
      
      detail_ = getDefaultInstance().getDetail();
      onChanged();
      return this;
    }
    /**
     * <code>optional string detail = 9;</code>
     */
    public Builder setDetailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      detail_ = value;
      onChanged();
      return this;
    }

    private boolean displayed_ ;
    /**
     * <code>optional bool displayed = 10;</code>
     */
    public boolean getDisplayed() {
      return displayed_;
    }
    /**
     * <code>optional bool displayed = 10;</code>
     */
    public Builder setDisplayed(boolean value) {
      
      displayed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool displayed = 10;</code>
     */
    public Builder clearDisplayed() {
      
      displayed_ = false;
      onChanged();
      return this;
    }

    private boolean deleted_ ;
    /**
     * <code>optional bool deleted = 11;</code>
     */
    public boolean getDeleted() {
      return deleted_;
    }
    /**
     * <code>optional bool deleted = 11;</code>
     */
    public Builder setDeleted(boolean value) {
      
      deleted_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool deleted = 11;</code>
     */
    public Builder clearDeleted() {
      
      deleted_ = false;
      onChanged();
      return this;
    }

    private java.util.List<io.reactivesw.catalog.grpc.GrpcAttribute> attribute_ =
      java.util.Collections.emptyList();
    private void ensureAttributeIsMutable() {
      if (!((bitField0_ & 0x00000800) == 0x00000800)) {
        attribute_ = new java.util.ArrayList<io.reactivesw.catalog.grpc.GrpcAttribute>(attribute_);
        bitField0_ |= 0x00000800;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.reactivesw.catalog.grpc.GrpcAttribute, io.reactivesw.catalog.grpc.GrpcAttribute.Builder, io.reactivesw.catalog.grpc.GrpcAttributeOrBuilder> attributeBuilder_;

    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
     */
    public java.util.List<io.reactivesw.catalog.grpc.GrpcAttribute> getAttributeList() {
      if (attributeBuilder_ == null) {
        return java.util.Collections.unmodifiableList(attribute_);
      } else {
        return attributeBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
     */
    public int getAttributeCount() {
      if (attributeBuilder_ == null) {
        return attribute_.size();
      } else {
        return attributeBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcAttribute getAttribute(int index) {
      if (attributeBuilder_ == null) {
        return attribute_.get(index);
      } else {
        return attributeBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
     */
    public Builder setAttribute(
        int index, io.reactivesw.catalog.grpc.GrpcAttribute value) {
      if (attributeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributeIsMutable();
        attribute_.set(index, value);
        onChanged();
      } else {
        attributeBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
     */
    public Builder setAttribute(
        int index, io.reactivesw.catalog.grpc.GrpcAttribute.Builder builderForValue) {
      if (attributeBuilder_ == null) {
        ensureAttributeIsMutable();
        attribute_.set(index, builderForValue.build());
        onChanged();
      } else {
        attributeBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
     */
    public Builder addAttribute(io.reactivesw.catalog.grpc.GrpcAttribute value) {
      if (attributeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributeIsMutable();
        attribute_.add(value);
        onChanged();
      } else {
        attributeBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
     */
    public Builder addAttribute(
        int index, io.reactivesw.catalog.grpc.GrpcAttribute value) {
      if (attributeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributeIsMutable();
        attribute_.add(index, value);
        onChanged();
      } else {
        attributeBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
     */
    public Builder addAttribute(
        io.reactivesw.catalog.grpc.GrpcAttribute.Builder builderForValue) {
      if (attributeBuilder_ == null) {
        ensureAttributeIsMutable();
        attribute_.add(builderForValue.build());
        onChanged();
      } else {
        attributeBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
     */
    public Builder addAttribute(
        int index, io.reactivesw.catalog.grpc.GrpcAttribute.Builder builderForValue) {
      if (attributeBuilder_ == null) {
        ensureAttributeIsMutable();
        attribute_.add(index, builderForValue.build());
        onChanged();
      } else {
        attributeBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
     */
    public Builder addAllAttribute(
        java.lang.Iterable<? extends io.reactivesw.catalog.grpc.GrpcAttribute> values) {
      if (attributeBuilder_ == null) {
        ensureAttributeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, attribute_);
        onChanged();
      } else {
        attributeBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
     */
    public Builder clearAttribute() {
      if (attributeBuilder_ == null) {
        attribute_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000800);
        onChanged();
      } else {
        attributeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
     */
    public Builder removeAttribute(int index) {
      if (attributeBuilder_ == null) {
        ensureAttributeIsMutable();
        attribute_.remove(index);
        onChanged();
      } else {
        attributeBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcAttribute.Builder getAttributeBuilder(
        int index) {
      return getAttributeFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcAttributeOrBuilder getAttributeOrBuilder(
        int index) {
      if (attributeBuilder_ == null) {
        return attribute_.get(index);  } else {
        return attributeBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
     */
    public java.util.List<? extends io.reactivesw.catalog.grpc.GrpcAttributeOrBuilder> 
         getAttributeOrBuilderList() {
      if (attributeBuilder_ != null) {
        return attributeBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(attribute_);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcAttribute.Builder addAttributeBuilder() {
      return getAttributeFieldBuilder().addBuilder(
          io.reactivesw.catalog.grpc.GrpcAttribute.getDefaultInstance());
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcAttribute.Builder addAttributeBuilder(
        int index) {
      return getAttributeFieldBuilder().addBuilder(
          index, io.reactivesw.catalog.grpc.GrpcAttribute.getDefaultInstance());
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
     */
    public java.util.List<io.reactivesw.catalog.grpc.GrpcAttribute.Builder> 
         getAttributeBuilderList() {
      return getAttributeFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.reactivesw.catalog.grpc.GrpcAttribute, io.reactivesw.catalog.grpc.GrpcAttribute.Builder, io.reactivesw.catalog.grpc.GrpcAttributeOrBuilder> 
        getAttributeFieldBuilder() {
      if (attributeBuilder_ == null) {
        attributeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.reactivesw.catalog.grpc.GrpcAttribute, io.reactivesw.catalog.grpc.GrpcAttribute.Builder, io.reactivesw.catalog.grpc.GrpcAttributeOrBuilder>(
                attribute_,
                ((bitField0_ & 0x00000800) == 0x00000800),
                getParentForChildren(),
                isClean());
        attribute_ = null;
      }
      return attributeBuilder_;
    }

    private java.util.List<io.reactivesw.catalog.grpc.GrpcSku> sku_ =
      java.util.Collections.emptyList();
    private void ensureSkuIsMutable() {
      if (!((bitField0_ & 0x00001000) == 0x00001000)) {
        sku_ = new java.util.ArrayList<io.reactivesw.catalog.grpc.GrpcSku>(sku_);
        bitField0_ |= 0x00001000;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.reactivesw.catalog.grpc.GrpcSku, io.reactivesw.catalog.grpc.GrpcSku.Builder, io.reactivesw.catalog.grpc.GrpcSkuOrBuilder> skuBuilder_;

    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
     */
    public java.util.List<io.reactivesw.catalog.grpc.GrpcSku> getSkuList() {
      if (skuBuilder_ == null) {
        return java.util.Collections.unmodifiableList(sku_);
      } else {
        return skuBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
     */
    public int getSkuCount() {
      if (skuBuilder_ == null) {
        return sku_.size();
      } else {
        return skuBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcSku getSku(int index) {
      if (skuBuilder_ == null) {
        return sku_.get(index);
      } else {
        return skuBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
     */
    public Builder setSku(
        int index, io.reactivesw.catalog.grpc.GrpcSku value) {
      if (skuBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSkuIsMutable();
        sku_.set(index, value);
        onChanged();
      } else {
        skuBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
     */
    public Builder setSku(
        int index, io.reactivesw.catalog.grpc.GrpcSku.Builder builderForValue) {
      if (skuBuilder_ == null) {
        ensureSkuIsMutable();
        sku_.set(index, builderForValue.build());
        onChanged();
      } else {
        skuBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
     */
    public Builder addSku(io.reactivesw.catalog.grpc.GrpcSku value) {
      if (skuBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSkuIsMutable();
        sku_.add(value);
        onChanged();
      } else {
        skuBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
     */
    public Builder addSku(
        int index, io.reactivesw.catalog.grpc.GrpcSku value) {
      if (skuBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSkuIsMutable();
        sku_.add(index, value);
        onChanged();
      } else {
        skuBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
     */
    public Builder addSku(
        io.reactivesw.catalog.grpc.GrpcSku.Builder builderForValue) {
      if (skuBuilder_ == null) {
        ensureSkuIsMutable();
        sku_.add(builderForValue.build());
        onChanged();
      } else {
        skuBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
     */
    public Builder addSku(
        int index, io.reactivesw.catalog.grpc.GrpcSku.Builder builderForValue) {
      if (skuBuilder_ == null) {
        ensureSkuIsMutable();
        sku_.add(index, builderForValue.build());
        onChanged();
      } else {
        skuBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
     */
    public Builder addAllSku(
        java.lang.Iterable<? extends io.reactivesw.catalog.grpc.GrpcSku> values) {
      if (skuBuilder_ == null) {
        ensureSkuIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sku_);
        onChanged();
      } else {
        skuBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
     */
    public Builder clearSku() {
      if (skuBuilder_ == null) {
        sku_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00001000);
        onChanged();
      } else {
        skuBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
     */
    public Builder removeSku(int index) {
      if (skuBuilder_ == null) {
        ensureSkuIsMutable();
        sku_.remove(index);
        onChanged();
      } else {
        skuBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcSku.Builder getSkuBuilder(
        int index) {
      return getSkuFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcSkuOrBuilder getSkuOrBuilder(
        int index) {
      if (skuBuilder_ == null) {
        return sku_.get(index);  } else {
        return skuBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
     */
    public java.util.List<? extends io.reactivesw.catalog.grpc.GrpcSkuOrBuilder> 
         getSkuOrBuilderList() {
      if (skuBuilder_ != null) {
        return skuBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(sku_);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcSku.Builder addSkuBuilder() {
      return getSkuFieldBuilder().addBuilder(
          io.reactivesw.catalog.grpc.GrpcSku.getDefaultInstance());
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcSku.Builder addSkuBuilder(
        int index) {
      return getSkuFieldBuilder().addBuilder(
          index, io.reactivesw.catalog.grpc.GrpcSku.getDefaultInstance());
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
     */
    public java.util.List<io.reactivesw.catalog.grpc.GrpcSku.Builder> 
         getSkuBuilderList() {
      return getSkuFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.reactivesw.catalog.grpc.GrpcSku, io.reactivesw.catalog.grpc.GrpcSku.Builder, io.reactivesw.catalog.grpc.GrpcSkuOrBuilder> 
        getSkuFieldBuilder() {
      if (skuBuilder_ == null) {
        skuBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.reactivesw.catalog.grpc.GrpcSku, io.reactivesw.catalog.grpc.GrpcSku.Builder, io.reactivesw.catalog.grpc.GrpcSkuOrBuilder>(
                sku_,
                ((bitField0_ & 0x00001000) == 0x00001000),
                getParentForChildren(),
                isClean());
        sku_ = null;
      }
      return skuBuilder_;
    }

    private java.util.List<io.reactivesw.catalog.grpc.GrpcVariant> variant_ =
      java.util.Collections.emptyList();
    private void ensureVariantIsMutable() {
      if (!((bitField0_ & 0x00002000) == 0x00002000)) {
        variant_ = new java.util.ArrayList<io.reactivesw.catalog.grpc.GrpcVariant>(variant_);
        bitField0_ |= 0x00002000;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.reactivesw.catalog.grpc.GrpcVariant, io.reactivesw.catalog.grpc.GrpcVariant.Builder, io.reactivesw.catalog.grpc.GrpcVariantOrBuilder> variantBuilder_;

    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
     */
    public java.util.List<io.reactivesw.catalog.grpc.GrpcVariant> getVariantList() {
      if (variantBuilder_ == null) {
        return java.util.Collections.unmodifiableList(variant_);
      } else {
        return variantBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
     */
    public int getVariantCount() {
      if (variantBuilder_ == null) {
        return variant_.size();
      } else {
        return variantBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcVariant getVariant(int index) {
      if (variantBuilder_ == null) {
        return variant_.get(index);
      } else {
        return variantBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
     */
    public Builder setVariant(
        int index, io.reactivesw.catalog.grpc.GrpcVariant value) {
      if (variantBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariantIsMutable();
        variant_.set(index, value);
        onChanged();
      } else {
        variantBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
     */
    public Builder setVariant(
        int index, io.reactivesw.catalog.grpc.GrpcVariant.Builder builderForValue) {
      if (variantBuilder_ == null) {
        ensureVariantIsMutable();
        variant_.set(index, builderForValue.build());
        onChanged();
      } else {
        variantBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
     */
    public Builder addVariant(io.reactivesw.catalog.grpc.GrpcVariant value) {
      if (variantBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariantIsMutable();
        variant_.add(value);
        onChanged();
      } else {
        variantBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
     */
    public Builder addVariant(
        int index, io.reactivesw.catalog.grpc.GrpcVariant value) {
      if (variantBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVariantIsMutable();
        variant_.add(index, value);
        onChanged();
      } else {
        variantBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
     */
    public Builder addVariant(
        io.reactivesw.catalog.grpc.GrpcVariant.Builder builderForValue) {
      if (variantBuilder_ == null) {
        ensureVariantIsMutable();
        variant_.add(builderForValue.build());
        onChanged();
      } else {
        variantBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
     */
    public Builder addVariant(
        int index, io.reactivesw.catalog.grpc.GrpcVariant.Builder builderForValue) {
      if (variantBuilder_ == null) {
        ensureVariantIsMutable();
        variant_.add(index, builderForValue.build());
        onChanged();
      } else {
        variantBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
     */
    public Builder addAllVariant(
        java.lang.Iterable<? extends io.reactivesw.catalog.grpc.GrpcVariant> values) {
      if (variantBuilder_ == null) {
        ensureVariantIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, variant_);
        onChanged();
      } else {
        variantBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
     */
    public Builder clearVariant() {
      if (variantBuilder_ == null) {
        variant_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00002000);
        onChanged();
      } else {
        variantBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
     */
    public Builder removeVariant(int index) {
      if (variantBuilder_ == null) {
        ensureVariantIsMutable();
        variant_.remove(index);
        onChanged();
      } else {
        variantBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcVariant.Builder getVariantBuilder(
        int index) {
      return getVariantFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcVariantOrBuilder getVariantOrBuilder(
        int index) {
      if (variantBuilder_ == null) {
        return variant_.get(index);  } else {
        return variantBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
     */
    public java.util.List<? extends io.reactivesw.catalog.grpc.GrpcVariantOrBuilder> 
         getVariantOrBuilderList() {
      if (variantBuilder_ != null) {
        return variantBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(variant_);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcVariant.Builder addVariantBuilder() {
      return getVariantFieldBuilder().addBuilder(
          io.reactivesw.catalog.grpc.GrpcVariant.getDefaultInstance());
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcVariant.Builder addVariantBuilder(
        int index) {
      return getVariantFieldBuilder().addBuilder(
          index, io.reactivesw.catalog.grpc.GrpcVariant.getDefaultInstance());
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
     */
    public java.util.List<io.reactivesw.catalog.grpc.GrpcVariant.Builder> 
         getVariantBuilderList() {
      return getVariantFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.reactivesw.catalog.grpc.GrpcVariant, io.reactivesw.catalog.grpc.GrpcVariant.Builder, io.reactivesw.catalog.grpc.GrpcVariantOrBuilder> 
        getVariantFieldBuilder() {
      if (variantBuilder_ == null) {
        variantBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.reactivesw.catalog.grpc.GrpcVariant, io.reactivesw.catalog.grpc.GrpcVariant.Builder, io.reactivesw.catalog.grpc.GrpcVariantOrBuilder>(
                variant_,
                ((bitField0_ & 0x00002000) == 0x00002000),
                getParentForChildren(),
                isClean());
        variant_ = null;
      }
      return variantBuilder_;
    }

    private java.util.List<io.reactivesw.catalog.grpc.GrpcFeature> feature_ =
      java.util.Collections.emptyList();
    private void ensureFeatureIsMutable() {
      if (!((bitField0_ & 0x00004000) == 0x00004000)) {
        feature_ = new java.util.ArrayList<io.reactivesw.catalog.grpc.GrpcFeature>(feature_);
        bitField0_ |= 0x00004000;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.reactivesw.catalog.grpc.GrpcFeature, io.reactivesw.catalog.grpc.GrpcFeature.Builder, io.reactivesw.catalog.grpc.GrpcFeatureOrBuilder> featureBuilder_;

    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
     */
    public java.util.List<io.reactivesw.catalog.grpc.GrpcFeature> getFeatureList() {
      if (featureBuilder_ == null) {
        return java.util.Collections.unmodifiableList(feature_);
      } else {
        return featureBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
     */
    public int getFeatureCount() {
      if (featureBuilder_ == null) {
        return feature_.size();
      } else {
        return featureBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcFeature getFeature(int index) {
      if (featureBuilder_ == null) {
        return feature_.get(index);
      } else {
        return featureBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
     */
    public Builder setFeature(
        int index, io.reactivesw.catalog.grpc.GrpcFeature value) {
      if (featureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFeatureIsMutable();
        feature_.set(index, value);
        onChanged();
      } else {
        featureBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
     */
    public Builder setFeature(
        int index, io.reactivesw.catalog.grpc.GrpcFeature.Builder builderForValue) {
      if (featureBuilder_ == null) {
        ensureFeatureIsMutable();
        feature_.set(index, builderForValue.build());
        onChanged();
      } else {
        featureBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
     */
    public Builder addFeature(io.reactivesw.catalog.grpc.GrpcFeature value) {
      if (featureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFeatureIsMutable();
        feature_.add(value);
        onChanged();
      } else {
        featureBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
     */
    public Builder addFeature(
        int index, io.reactivesw.catalog.grpc.GrpcFeature value) {
      if (featureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFeatureIsMutable();
        feature_.add(index, value);
        onChanged();
      } else {
        featureBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
     */
    public Builder addFeature(
        io.reactivesw.catalog.grpc.GrpcFeature.Builder builderForValue) {
      if (featureBuilder_ == null) {
        ensureFeatureIsMutable();
        feature_.add(builderForValue.build());
        onChanged();
      } else {
        featureBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
     */
    public Builder addFeature(
        int index, io.reactivesw.catalog.grpc.GrpcFeature.Builder builderForValue) {
      if (featureBuilder_ == null) {
        ensureFeatureIsMutable();
        feature_.add(index, builderForValue.build());
        onChanged();
      } else {
        featureBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
     */
    public Builder addAllFeature(
        java.lang.Iterable<? extends io.reactivesw.catalog.grpc.GrpcFeature> values) {
      if (featureBuilder_ == null) {
        ensureFeatureIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, feature_);
        onChanged();
      } else {
        featureBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
     */
    public Builder clearFeature() {
      if (featureBuilder_ == null) {
        feature_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00004000);
        onChanged();
      } else {
        featureBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
     */
    public Builder removeFeature(int index) {
      if (featureBuilder_ == null) {
        ensureFeatureIsMutable();
        feature_.remove(index);
        onChanged();
      } else {
        featureBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcFeature.Builder getFeatureBuilder(
        int index) {
      return getFeatureFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcFeatureOrBuilder getFeatureOrBuilder(
        int index) {
      if (featureBuilder_ == null) {
        return feature_.get(index);  } else {
        return featureBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
     */
    public java.util.List<? extends io.reactivesw.catalog.grpc.GrpcFeatureOrBuilder> 
         getFeatureOrBuilderList() {
      if (featureBuilder_ != null) {
        return featureBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(feature_);
      }
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcFeature.Builder addFeatureBuilder() {
      return getFeatureFieldBuilder().addBuilder(
          io.reactivesw.catalog.grpc.GrpcFeature.getDefaultInstance());
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
     */
    public io.reactivesw.catalog.grpc.GrpcFeature.Builder addFeatureBuilder(
        int index) {
      return getFeatureFieldBuilder().addBuilder(
          index, io.reactivesw.catalog.grpc.GrpcFeature.getDefaultInstance());
    }
    /**
     * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
     */
    public java.util.List<io.reactivesw.catalog.grpc.GrpcFeature.Builder> 
         getFeatureBuilderList() {
      return getFeatureFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.reactivesw.catalog.grpc.GrpcFeature, io.reactivesw.catalog.grpc.GrpcFeature.Builder, io.reactivesw.catalog.grpc.GrpcFeatureOrBuilder> 
        getFeatureFieldBuilder() {
      if (featureBuilder_ == null) {
        featureBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.reactivesw.catalog.grpc.GrpcFeature, io.reactivesw.catalog.grpc.GrpcFeature.Builder, io.reactivesw.catalog.grpc.GrpcFeatureOrBuilder>(
                feature_,
                ((bitField0_ & 0x00004000) == 0x00004000),
                getParentForChildren(),
                isClean());
        feature_ = null;
      }
      return featureBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:io.reactivesw.catalog.infrastructure.GrpcProduct)
  }

  // @@protoc_insertion_point(class_scope:io.reactivesw.catalog.infrastructure.GrpcProduct)
  private static final io.reactivesw.catalog.grpc.GrpcProduct DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.reactivesw.catalog.grpc.GrpcProduct();
  }

  public static io.reactivesw.catalog.grpc.GrpcProduct getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GrpcProduct>
      PARSER = new com.google.protobuf.AbstractParser<GrpcProduct>() {
    public GrpcProduct parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new GrpcProduct(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GrpcProduct> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GrpcProduct> getParserForType() {
    return PARSER;
  }

  public io.reactivesw.catalog.grpc.GrpcProduct getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

