// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog_proto/catalog_message.proto

package io.reactivesw.catalog.grpc;

public interface GrpcSkuOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.reactivesw.catalog.infrastructure.GrpcSku)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>optional string skuNumber = 2;</code>
   */
  java.lang.String getSkuNumber();
  /**
   * <code>optional string skuNumber = 2;</code>
   */
  com.google.protobuf.ByteString
      getSkuNumberBytes();

  /**
   * <code>optional bool isActive = 3;</code>
   */
  boolean getIsActive();

  /**
   * <code>optional int32 quatity = 4;</code>
   */
  int getQuatity();

  /**
   * <code>optional string upc = 5;</code>
   */
  java.lang.String getUpc();
  /**
   * <code>optional string upc = 5;</code>
   */
  com.google.protobuf.ByteString
      getUpcBytes();

  /**
   * <code>optional int32 display_order = 6;</code>
   */
  int getDisplayOrder();

  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
   */
  java.util.List<io.reactivesw.catalog.grpc.GrpcMedia> 
      getMediaList();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
   */
  io.reactivesw.catalog.grpc.GrpcMedia getMedia(int index);
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
   */
  int getMediaCount();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
   */
  java.util.List<? extends io.reactivesw.catalog.grpc.GrpcMediaOrBuilder> 
      getMediaOrBuilderList();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcMedia media = 7;</code>
   */
  io.reactivesw.catalog.grpc.GrpcMediaOrBuilder getMediaOrBuilder(
      int index);

  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
   */
  java.util.List<io.reactivesw.catalog.grpc.GrpcVariantValue> 
      getVariantValueList();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
   */
  io.reactivesw.catalog.grpc.GrpcVariantValue getVariantValue(int index);
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
   */
  int getVariantValueCount();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
   */
  java.util.List<? extends io.reactivesw.catalog.grpc.GrpcVariantValueOrBuilder> 
      getVariantValueOrBuilderList();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 8;</code>
   */
  io.reactivesw.catalog.grpc.GrpcVariantValueOrBuilder getVariantValueOrBuilder(
      int index);
}
