// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog_proto/catalog_message.proto

package io.reactivesw.catalog.grpc;

public interface GrpcProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.reactivesw.catalog.infrastructure.GrpcProduct)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>optional string manufacturer = 2;</code>
   */
  java.lang.String getManufacturer();
  /**
   * <code>optional string manufacturer = 2;</code>
   */
  com.google.protobuf.ByteString
      getManufacturerBytes();

  /**
   * <code>optional string brand = 3;</code>
   */
  java.lang.String getBrand();
  /**
   * <code>optional string brand = 3;</code>
   */
  com.google.protobuf.ByteString
      getBrandBytes();

  /**
   * <code>optional string model = 4;</code>
   */
  java.lang.String getModel();
  /**
   * <code>optional string model = 4;</code>
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <code>optional string name = 5;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 5;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string price = 6;</code>
   */
  java.lang.String getPrice();
  /**
   * <code>optional string price = 6;</code>
   */
  com.google.protobuf.ByteString
      getPriceBytes();

  /**
   * <code>optional int32 display_order = 7;</code>
   */
  int getDisplayOrder();

  /**
   * <code>optional string description = 8;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>optional string description = 8;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>optional string detail = 9;</code>
   */
  java.lang.String getDetail();
  /**
   * <code>optional string detail = 9;</code>
   */
  com.google.protobuf.ByteString
      getDetailBytes();

  /**
   * <code>optional bool displayed = 10;</code>
   */
  boolean getDisplayed();

  /**
   * <code>optional bool deleted = 11;</code>
   */
  boolean getDeleted();

  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
   */
  java.util.List<io.reactivesw.catalog.grpc.GrpcAttribute> 
      getAttributeList();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
   */
  io.reactivesw.catalog.grpc.GrpcAttribute getAttribute(int index);
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
   */
  int getAttributeCount();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
   */
  java.util.List<? extends io.reactivesw.catalog.grpc.GrpcAttributeOrBuilder> 
      getAttributeOrBuilderList();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcAttribute attribute = 12;</code>
   */
  io.reactivesw.catalog.grpc.GrpcAttributeOrBuilder getAttributeOrBuilder(
      int index);

  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
   */
  java.util.List<io.reactivesw.catalog.grpc.GrpcSku> 
      getSkuList();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
   */
  io.reactivesw.catalog.grpc.GrpcSku getSku(int index);
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
   */
  int getSkuCount();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
   */
  java.util.List<? extends io.reactivesw.catalog.grpc.GrpcSkuOrBuilder> 
      getSkuOrBuilderList();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcSku sku = 13;</code>
   */
  io.reactivesw.catalog.grpc.GrpcSkuOrBuilder getSkuOrBuilder(
      int index);

  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
   */
  java.util.List<io.reactivesw.catalog.grpc.GrpcVariant> 
      getVariantList();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
   */
  io.reactivesw.catalog.grpc.GrpcVariant getVariant(int index);
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
   */
  int getVariantCount();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
   */
  java.util.List<? extends io.reactivesw.catalog.grpc.GrpcVariantOrBuilder> 
      getVariantOrBuilderList();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariant variant = 14;</code>
   */
  io.reactivesw.catalog.grpc.GrpcVariantOrBuilder getVariantOrBuilder(
      int index);

  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
   */
  java.util.List<io.reactivesw.catalog.grpc.GrpcFeature> 
      getFeatureList();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
   */
  io.reactivesw.catalog.grpc.GrpcFeature getFeature(int index);
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
   */
  int getFeatureCount();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
   */
  java.util.List<? extends io.reactivesw.catalog.grpc.GrpcFeatureOrBuilder> 
      getFeatureOrBuilderList();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcFeature feature = 15;</code>
   */
  io.reactivesw.catalog.grpc.GrpcFeatureOrBuilder getFeatureOrBuilder(
      int index);
}
