// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog_proto/catalog_message.proto

package io.reactivesw.catalog.grpc;

public interface GrpcVariantOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.reactivesw.catalog.infrastructure.GrpcVariant)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 display_order = 3;</code>
   */
  int getDisplayOrder();

  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 4;</code>
   */
  java.util.List<io.reactivesw.catalog.grpc.GrpcVariantValue> 
      getVariantValueList();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 4;</code>
   */
  io.reactivesw.catalog.grpc.GrpcVariantValue getVariantValue(int index);
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 4;</code>
   */
  int getVariantValueCount();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 4;</code>
   */
  java.util.List<? extends io.reactivesw.catalog.grpc.GrpcVariantValueOrBuilder> 
      getVariantValueOrBuilderList();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcVariantValue variant_value = 4;</code>
   */
  io.reactivesw.catalog.grpc.GrpcVariantValueOrBuilder getVariantValueOrBuilder(
      int index);
}
