// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog_proto/catalog_message.proto

package io.reactivesw.catalog.grpc;

public interface ProductBriefListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.reactivesw.catalog.infrastructure.ProductBriefList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcProductBrief product_brief = 1;</code>
   */
  java.util.List<io.reactivesw.catalog.grpc.GrpcProductBrief> 
      getProductBriefList();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcProductBrief product_brief = 1;</code>
   */
  io.reactivesw.catalog.grpc.GrpcProductBrief getProductBrief(int index);
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcProductBrief product_brief = 1;</code>
   */
  int getProductBriefCount();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcProductBrief product_brief = 1;</code>
   */
  java.util.List<? extends io.reactivesw.catalog.grpc.GrpcProductBriefOrBuilder> 
      getProductBriefOrBuilderList();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.GrpcProductBrief product_brief = 1;</code>
   */
  io.reactivesw.catalog.grpc.GrpcProductBriefOrBuilder getProductBriefOrBuilder(
      int index);
}
