// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog_proto/catalog_sku_message.proto

package io.reactivesw.catalog.grpc;

/**
 * <pre>
 **
 * request message for querySkuSimpleInformation.
 * </pre>
 *
 * Protobuf type {@code io.reactivesw.catalog.infrastructure.SkuIdList}
 */
public  final class SkuIdList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.reactivesw.catalog.infrastructure.SkuIdList)
    SkuIdListOrBuilder {
  // Use SkuIdList.newBuilder() to construct.
  private SkuIdList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SkuIdList() {
    skuId_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SkuIdList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              skuId_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000001;
            }
            skuId_.add(input.readInt64());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
              skuId_ = new java.util.ArrayList<java.lang.Long>();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              skuId_.add(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        skuId_ = java.util.Collections.unmodifiableList(skuId_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.reactivesw.catalog.grpc.CatalogSkuMessage.internal_static_io_reactivesw_catalog_infrastructure_SkuIdList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.reactivesw.catalog.grpc.CatalogSkuMessage.internal_static_io_reactivesw_catalog_infrastructure_SkuIdList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.reactivesw.catalog.grpc.SkuIdList.class, io.reactivesw.catalog.grpc.SkuIdList.Builder.class);
  }

  public static final int SKU_ID_FIELD_NUMBER = 1;
  private java.util.List<java.lang.Long> skuId_;
  /**
   * <code>repeated int64 sku_id = 1;</code>
   */
  public java.util.List<java.lang.Long>
      getSkuIdList() {
    return skuId_;
  }
  /**
   * <code>repeated int64 sku_id = 1;</code>
   */
  public int getSkuIdCount() {
    return skuId_.size();
  }
  /**
   * <code>repeated int64 sku_id = 1;</code>
   */
  public long getSkuId(int index) {
    return skuId_.get(index);
  }
  private int skuIdMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getSkuIdList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(skuIdMemoizedSerializedSize);
    }
    for (int i = 0; i < skuId_.size(); i++) {
      output.writeInt64NoTag(skuId_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < skuId_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(skuId_.get(i));
      }
      size += dataSize;
      if (!getSkuIdList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      skuIdMemoizedSerializedSize = dataSize;
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.reactivesw.catalog.grpc.SkuIdList)) {
      return super.equals(obj);
    }
    io.reactivesw.catalog.grpc.SkuIdList other = (io.reactivesw.catalog.grpc.SkuIdList) obj;

    boolean result = true;
    result = result && getSkuIdList()
        .equals(other.getSkuIdList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getSkuIdCount() > 0) {
      hash = (37 * hash) + SKU_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSkuIdList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.reactivesw.catalog.grpc.SkuIdList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.reactivesw.catalog.grpc.SkuIdList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.reactivesw.catalog.grpc.SkuIdList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.reactivesw.catalog.grpc.SkuIdList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.reactivesw.catalog.grpc.SkuIdList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.reactivesw.catalog.grpc.SkuIdList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.reactivesw.catalog.grpc.SkuIdList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.reactivesw.catalog.grpc.SkuIdList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.reactivesw.catalog.grpc.SkuIdList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.reactivesw.catalog.grpc.SkuIdList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.reactivesw.catalog.grpc.SkuIdList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * request message for querySkuSimpleInformation.
   * </pre>
   *
   * Protobuf type {@code io.reactivesw.catalog.infrastructure.SkuIdList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.reactivesw.catalog.infrastructure.SkuIdList)
      io.reactivesw.catalog.grpc.SkuIdListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.reactivesw.catalog.grpc.CatalogSkuMessage.internal_static_io_reactivesw_catalog_infrastructure_SkuIdList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.reactivesw.catalog.grpc.CatalogSkuMessage.internal_static_io_reactivesw_catalog_infrastructure_SkuIdList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.reactivesw.catalog.grpc.SkuIdList.class, io.reactivesw.catalog.grpc.SkuIdList.Builder.class);
    }

    // Construct using io.reactivesw.catalog.grpc.SkuIdList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      skuId_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.reactivesw.catalog.grpc.CatalogSkuMessage.internal_static_io_reactivesw_catalog_infrastructure_SkuIdList_descriptor;
    }

    public io.reactivesw.catalog.grpc.SkuIdList getDefaultInstanceForType() {
      return io.reactivesw.catalog.grpc.SkuIdList.getDefaultInstance();
    }

    public io.reactivesw.catalog.grpc.SkuIdList build() {
      io.reactivesw.catalog.grpc.SkuIdList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.reactivesw.catalog.grpc.SkuIdList buildPartial() {
      io.reactivesw.catalog.grpc.SkuIdList result = new io.reactivesw.catalog.grpc.SkuIdList(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        skuId_ = java.util.Collections.unmodifiableList(skuId_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.skuId_ = skuId_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.reactivesw.catalog.grpc.SkuIdList) {
        return mergeFrom((io.reactivesw.catalog.grpc.SkuIdList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.reactivesw.catalog.grpc.SkuIdList other) {
      if (other == io.reactivesw.catalog.grpc.SkuIdList.getDefaultInstance()) return this;
      if (!other.skuId_.isEmpty()) {
        if (skuId_.isEmpty()) {
          skuId_ = other.skuId_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureSkuIdIsMutable();
          skuId_.addAll(other.skuId_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.reactivesw.catalog.grpc.SkuIdList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.reactivesw.catalog.grpc.SkuIdList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<java.lang.Long> skuId_ = java.util.Collections.emptyList();
    private void ensureSkuIdIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        skuId_ = new java.util.ArrayList<java.lang.Long>(skuId_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int64 sku_id = 1;</code>
     */
    public java.util.List<java.lang.Long>
        getSkuIdList() {
      return java.util.Collections.unmodifiableList(skuId_);
    }
    /**
     * <code>repeated int64 sku_id = 1;</code>
     */
    public int getSkuIdCount() {
      return skuId_.size();
    }
    /**
     * <code>repeated int64 sku_id = 1;</code>
     */
    public long getSkuId(int index) {
      return skuId_.get(index);
    }
    /**
     * <code>repeated int64 sku_id = 1;</code>
     */
    public Builder setSkuId(
        int index, long value) {
      ensureSkuIdIsMutable();
      skuId_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 sku_id = 1;</code>
     */
    public Builder addSkuId(long value) {
      ensureSkuIdIsMutable();
      skuId_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 sku_id = 1;</code>
     */
    public Builder addAllSkuId(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureSkuIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, skuId_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 sku_id = 1;</code>
     */
    public Builder clearSkuId() {
      skuId_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:io.reactivesw.catalog.infrastructure.SkuIdList)
  }

  // @@protoc_insertion_point(class_scope:io.reactivesw.catalog.infrastructure.SkuIdList)
  private static final io.reactivesw.catalog.grpc.SkuIdList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.reactivesw.catalog.grpc.SkuIdList();
  }

  public static io.reactivesw.catalog.grpc.SkuIdList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SkuIdList>
      PARSER = new com.google.protobuf.AbstractParser<SkuIdList>() {
    public SkuIdList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SkuIdList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SkuIdList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SkuIdList> getParserForType() {
    return PARSER;
  }

  public io.reactivesw.catalog.grpc.SkuIdList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

