// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog_proto/catalog_sku_message.proto

package io.reactivesw.catalog.grpc;

public interface SkuInformationListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.reactivesw.catalog.infrastructure.SkuInformationList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.SkuInformation sku_information = 1;</code>
   */
  java.util.List<io.reactivesw.catalog.grpc.SkuInformation> 
      getSkuInformationList();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.SkuInformation sku_information = 1;</code>
   */
  io.reactivesw.catalog.grpc.SkuInformation getSkuInformation(int index);
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.SkuInformation sku_information = 1;</code>
   */
  int getSkuInformationCount();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.SkuInformation sku_information = 1;</code>
   */
  java.util.List<? extends io.reactivesw.catalog.grpc.SkuInformationOrBuilder> 
      getSkuInformationOrBuilderList();
  /**
   * <code>repeated .io.reactivesw.catalog.infrastructure.SkuInformation sku_information = 1;</code>
   */
  io.reactivesw.catalog.grpc.SkuInformationOrBuilder getSkuInformationOrBuilder(
      int index);
}
