// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog_proto/catalog_sku_message.proto

package io.reactivesw.catalog.grpc;

/**
 * <pre>
 **
 * message for sku.
 * response when call querySkuSimpleInformation.
 * </pre>
 *
 * Protobuf type {@code io.reactivesw.catalog.infrastructure.SkuInformation}
 */
public  final class SkuInformation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.reactivesw.catalog.infrastructure.SkuInformation)
    SkuInformationOrBuilder {
  // Use SkuInformation.newBuilder() to construct.
  private SkuInformation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SkuInformation() {
    skuId_ = 0L;
    skuNumber_ = "";
    skuName_ = "";
    mediaUrl_ = "";
    price_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SkuInformation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            skuId_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            skuNumber_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            skuName_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            mediaUrl_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            price_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.reactivesw.catalog.grpc.CatalogSkuMessage.internal_static_io_reactivesw_catalog_infrastructure_SkuInformation_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.reactivesw.catalog.grpc.CatalogSkuMessage.internal_static_io_reactivesw_catalog_infrastructure_SkuInformation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.reactivesw.catalog.grpc.SkuInformation.class, io.reactivesw.catalog.grpc.SkuInformation.Builder.class);
  }

  public static final int SKU_ID_FIELD_NUMBER = 1;
  private long skuId_;
  /**
   * <code>optional int64 sku_id = 1;</code>
   */
  public long getSkuId() {
    return skuId_;
  }

  public static final int SKU_NUMBER_FIELD_NUMBER = 2;
  private volatile java.lang.Object skuNumber_;
  /**
   * <code>optional string sku_number = 2;</code>
   */
  public java.lang.String getSkuNumber() {
    java.lang.Object ref = skuNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      skuNumber_ = s;
      return s;
    }
  }
  /**
   * <code>optional string sku_number = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSkuNumberBytes() {
    java.lang.Object ref = skuNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      skuNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SKU_NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object skuName_;
  /**
   * <code>optional string sku_name = 3;</code>
   */
  public java.lang.String getSkuName() {
    java.lang.Object ref = skuName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      skuName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string sku_name = 3;</code>
   */
  public com.google.protobuf.ByteString
      getSkuNameBytes() {
    java.lang.Object ref = skuName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      skuName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MEDIA_URL_FIELD_NUMBER = 4;
  private volatile java.lang.Object mediaUrl_;
  /**
   * <code>optional string media_url = 4;</code>
   */
  public java.lang.String getMediaUrl() {
    java.lang.Object ref = mediaUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mediaUrl_ = s;
      return s;
    }
  }
  /**
   * <code>optional string media_url = 4;</code>
   */
  public com.google.protobuf.ByteString
      getMediaUrlBytes() {
    java.lang.Object ref = mediaUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mediaUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRICE_FIELD_NUMBER = 5;
  private volatile java.lang.Object price_;
  /**
   * <code>optional string price = 5;</code>
   */
  public java.lang.String getPrice() {
    java.lang.Object ref = price_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      price_ = s;
      return s;
    }
  }
  /**
   * <code>optional string price = 5;</code>
   */
  public com.google.protobuf.ByteString
      getPriceBytes() {
    java.lang.Object ref = price_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      price_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (skuId_ != 0L) {
      output.writeInt64(1, skuId_);
    }
    if (!getSkuNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, skuNumber_);
    }
    if (!getSkuNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, skuName_);
    }
    if (!getMediaUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, mediaUrl_);
    }
    if (!getPriceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, price_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (skuId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, skuId_);
    }
    if (!getSkuNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, skuNumber_);
    }
    if (!getSkuNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, skuName_);
    }
    if (!getMediaUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, mediaUrl_);
    }
    if (!getPriceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, price_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.reactivesw.catalog.grpc.SkuInformation)) {
      return super.equals(obj);
    }
    io.reactivesw.catalog.grpc.SkuInformation other = (io.reactivesw.catalog.grpc.SkuInformation) obj;

    boolean result = true;
    result = result && (getSkuId()
        == other.getSkuId());
    result = result && getSkuNumber()
        .equals(other.getSkuNumber());
    result = result && getSkuName()
        .equals(other.getSkuName());
    result = result && getMediaUrl()
        .equals(other.getMediaUrl());
    result = result && getPrice()
        .equals(other.getPrice());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + SKU_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSkuId());
    hash = (37 * hash) + SKU_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getSkuNumber().hashCode();
    hash = (37 * hash) + SKU_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getSkuName().hashCode();
    hash = (37 * hash) + MEDIA_URL_FIELD_NUMBER;
    hash = (53 * hash) + getMediaUrl().hashCode();
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + getPrice().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.reactivesw.catalog.grpc.SkuInformation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.reactivesw.catalog.grpc.SkuInformation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.reactivesw.catalog.grpc.SkuInformation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.reactivesw.catalog.grpc.SkuInformation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.reactivesw.catalog.grpc.SkuInformation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.reactivesw.catalog.grpc.SkuInformation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.reactivesw.catalog.grpc.SkuInformation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.reactivesw.catalog.grpc.SkuInformation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.reactivesw.catalog.grpc.SkuInformation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.reactivesw.catalog.grpc.SkuInformation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.reactivesw.catalog.grpc.SkuInformation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * message for sku.
   * response when call querySkuSimpleInformation.
   * </pre>
   *
   * Protobuf type {@code io.reactivesw.catalog.infrastructure.SkuInformation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.reactivesw.catalog.infrastructure.SkuInformation)
      io.reactivesw.catalog.grpc.SkuInformationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.reactivesw.catalog.grpc.CatalogSkuMessage.internal_static_io_reactivesw_catalog_infrastructure_SkuInformation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.reactivesw.catalog.grpc.CatalogSkuMessage.internal_static_io_reactivesw_catalog_infrastructure_SkuInformation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.reactivesw.catalog.grpc.SkuInformation.class, io.reactivesw.catalog.grpc.SkuInformation.Builder.class);
    }

    // Construct using io.reactivesw.catalog.grpc.SkuInformation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      skuId_ = 0L;

      skuNumber_ = "";

      skuName_ = "";

      mediaUrl_ = "";

      price_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.reactivesw.catalog.grpc.CatalogSkuMessage.internal_static_io_reactivesw_catalog_infrastructure_SkuInformation_descriptor;
    }

    public io.reactivesw.catalog.grpc.SkuInformation getDefaultInstanceForType() {
      return io.reactivesw.catalog.grpc.SkuInformation.getDefaultInstance();
    }

    public io.reactivesw.catalog.grpc.SkuInformation build() {
      io.reactivesw.catalog.grpc.SkuInformation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.reactivesw.catalog.grpc.SkuInformation buildPartial() {
      io.reactivesw.catalog.grpc.SkuInformation result = new io.reactivesw.catalog.grpc.SkuInformation(this);
      result.skuId_ = skuId_;
      result.skuNumber_ = skuNumber_;
      result.skuName_ = skuName_;
      result.mediaUrl_ = mediaUrl_;
      result.price_ = price_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.reactivesw.catalog.grpc.SkuInformation) {
        return mergeFrom((io.reactivesw.catalog.grpc.SkuInformation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.reactivesw.catalog.grpc.SkuInformation other) {
      if (other == io.reactivesw.catalog.grpc.SkuInformation.getDefaultInstance()) return this;
      if (other.getSkuId() != 0L) {
        setSkuId(other.getSkuId());
      }
      if (!other.getSkuNumber().isEmpty()) {
        skuNumber_ = other.skuNumber_;
        onChanged();
      }
      if (!other.getSkuName().isEmpty()) {
        skuName_ = other.skuName_;
        onChanged();
      }
      if (!other.getMediaUrl().isEmpty()) {
        mediaUrl_ = other.mediaUrl_;
        onChanged();
      }
      if (!other.getPrice().isEmpty()) {
        price_ = other.price_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.reactivesw.catalog.grpc.SkuInformation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.reactivesw.catalog.grpc.SkuInformation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long skuId_ ;
    /**
     * <code>optional int64 sku_id = 1;</code>
     */
    public long getSkuId() {
      return skuId_;
    }
    /**
     * <code>optional int64 sku_id = 1;</code>
     */
    public Builder setSkuId(long value) {
      
      skuId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 sku_id = 1;</code>
     */
    public Builder clearSkuId() {
      
      skuId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object skuNumber_ = "";
    /**
     * <code>optional string sku_number = 2;</code>
     */
    public java.lang.String getSkuNumber() {
      java.lang.Object ref = skuNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        skuNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string sku_number = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSkuNumberBytes() {
      java.lang.Object ref = skuNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        skuNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string sku_number = 2;</code>
     */
    public Builder setSkuNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      skuNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string sku_number = 2;</code>
     */
    public Builder clearSkuNumber() {
      
      skuNumber_ = getDefaultInstance().getSkuNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional string sku_number = 2;</code>
     */
    public Builder setSkuNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      skuNumber_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object skuName_ = "";
    /**
     * <code>optional string sku_name = 3;</code>
     */
    public java.lang.String getSkuName() {
      java.lang.Object ref = skuName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        skuName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string sku_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSkuNameBytes() {
      java.lang.Object ref = skuName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        skuName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string sku_name = 3;</code>
     */
    public Builder setSkuName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      skuName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string sku_name = 3;</code>
     */
    public Builder clearSkuName() {
      
      skuName_ = getDefaultInstance().getSkuName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string sku_name = 3;</code>
     */
    public Builder setSkuNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      skuName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object mediaUrl_ = "";
    /**
     * <code>optional string media_url = 4;</code>
     */
    public java.lang.String getMediaUrl() {
      java.lang.Object ref = mediaUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mediaUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string media_url = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMediaUrlBytes() {
      java.lang.Object ref = mediaUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mediaUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string media_url = 4;</code>
     */
    public Builder setMediaUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mediaUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string media_url = 4;</code>
     */
    public Builder clearMediaUrl() {
      
      mediaUrl_ = getDefaultInstance().getMediaUrl();
      onChanged();
      return this;
    }
    /**
     * <code>optional string media_url = 4;</code>
     */
    public Builder setMediaUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mediaUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object price_ = "";
    /**
     * <code>optional string price = 5;</code>
     */
    public java.lang.String getPrice() {
      java.lang.Object ref = price_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        price_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string price = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPriceBytes() {
      java.lang.Object ref = price_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        price_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string price = 5;</code>
     */
    public Builder setPrice(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string price = 5;</code>
     */
    public Builder clearPrice() {
      
      price_ = getDefaultInstance().getPrice();
      onChanged();
      return this;
    }
    /**
     * <code>optional string price = 5;</code>
     */
    public Builder setPriceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      price_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:io.reactivesw.catalog.infrastructure.SkuInformation)
  }

  // @@protoc_insertion_point(class_scope:io.reactivesw.catalog.infrastructure.SkuInformation)
  private static final io.reactivesw.catalog.grpc.SkuInformation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.reactivesw.catalog.grpc.SkuInformation();
  }

  public static io.reactivesw.catalog.grpc.SkuInformation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SkuInformation>
      PARSER = new com.google.protobuf.AbstractParser<SkuInformation>() {
    public SkuInformation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SkuInformation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SkuInformation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SkuInformation> getParserForType() {
    return PARSER;
  }

  public io.reactivesw.catalog.grpc.SkuInformation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

